:page-title     : Machine Learning Week-1 (Coursera)
:page-signed-by : Deo Valiandro. M <valiandrod@gmail.com>
:page-layout    : default
:page-category  : ml
:page-time      : 2022-05-12T14:08:30
:page-update    : 2022-05-12T14:08:30


Dulu saya mengambil mata kuliah ML, tetapi kemudian berganti fokus ke
kriptografi, jadi untuk mempelajari materi lagi, saya ikut kelas Coursera.

== Intro

Machine Learning adalah mesin yang mempelajari data berdasarkan pengalaman,
dengan memperhatikan beberapa kelas dari suatu tugas tertentu.

Terbagi menjadi:

=== Supervised Learning

Diberikan dataset yang telah diketahui hasilnya bagaimana dan diberikan tugas
untuk menentukan korelasi data jika diberikan suatu input diluar data yang telah
ada.

Dikategorikan menjadi:

. regression, memprediksi hasil continui,  misalnya memprediksi harga rumah.
. classification, memprediksi hasil diskrit, misalnya memprediksi tumor ganas
atau tumor jinak.

=== Unsupervised Learning

Diberikan data yang tidak diketahui, kemudian dilakukan pengelompokan data.
Hasilnya adalah struktur data. Kita dapat melakukannya dengan melakukan klustering
atau clustering data berdasarkan variabelnya.

Contoh:

. Clusetering, diberikan data gen kemudian dikelompokkan berdasarkan variabel,
seperti lokasi, masa hidup, dll.
. Non-clustering, menemukan struktur dari data chaos, misalnya "Cocktail Party
Algorithm", identifying individual voices and music from a mesh of sounds at a
cocktail party.