= Pasal-pasal Ajaran Dordrecht
:page-category: christianity

== I. Pemilihan dan penolakan ilahi

. Semua orang telah berdosa di dalam Adam, dan patut menerima hukuman, yaitu
kutuk Allah dan kematian yang kekal. Oleh karena itu, Allah tidak akan berbuat
tidak adil terhadap siapapun, seandainya Dia telah memutuskan untuk membiarkan
segenap umat manusia dalam dosa dan kutuk serta menghukumnya karena dosa, sesuai
dengan perkataan Sang Rasul, 'Seluruh dunia jatuh ke bawah hukuman Allah. Karena
semua orang telah berbuat dosa dan telah kehilangan kemuliaan Allah.'
(Rom 3:19,23). Dan, 'Upah dosa ialah maut.'(Rom 6:23)

. Akan tetapi, dalam hal inilah kasih Allah dinyatakan, yaitu, bahwa Dia telah
mengutus Anak-Nya yang tunggal ke dalam dunia, supaya setiap orang yang percaya
kepada-Nya tidak binasa, tetapi beroleh hidup yang kekal.

. Maka agar manusia dihantarkan pada iman, Allah berkenan mengutus
pewarta-pewarta kabar yang amat gembira itu kepada siapa yang dikehendaki-Nya
dan bilamana Dia menghendakinya. Oleh pelayanan mereka itu manusia dipanggil
untuk bertobat dan percaya kepada Kristus yang disalibkan itu. Karena,
'bagaimana mereka dapat percaya kepada Dia, jika mereka tidak mendengar tentang
Dia? Bagaimana mereka dapat mendengar tentang Dia, jika tidak ada yang
memberitakan-Nya? Dan bagaimana mereka dapat memberitakan-Nya, jika mereka tidak
diutus?' (Rom 10:14-15).

. Adapun mereka tidak percaya kepada Injil itu, murka Allah tetap berada di atas
mereka. Sebaliknya, mereka yang menerimanya, dan yang memeluk Juruselamat Yesus
dengan iman yang sejati dan hidup, akan dilepaskan oleh-Nya dari murka Allah dan
kebinasaan serta dikaruniai hidup yang kekal.

. Yang menjadi penyebab ketidakpercayaan itu dan yang harus dipersalahkan
karenanya sama sekali bukan Allah, melainkan manusia, sama seperti dalam hal
semua dosa lainnya. Sebaliknya, iman kepada Yesus Kristus dan keselamatan
oleh-Nya adalah pemberian Allah yang cuma-cuma, seperti tertulis, 'Sebab karena
kasih karunia kamu diselamatkan oleh iman; itu bukan hasil usahamu, tetapi
pemberian Allah' (Efe 2:8). Juga, 'Sebab kepada kamu dikaruniakan untuk percaya
kepada Kristus.' (Fil 1:29).

. Kepada orang-orang tertentu Allah mengaruniakan iman dalam hidup ini, kepada
orang lain tidak. Hal ini timbul dari keputusan-Nya yang kekal. 'Karena semua
karya-Nya telah diketahui-Nya sejak semula' (Kis 15:18), dan, 'Segala sesuatu
dikerjakan-Nya menurut keputusan kehendak-Nya' (Efe 1:11). Menurut keputusan
ini, hati orang pilihan dilunakkan-Nya dengan penuh rahmat dan ditundukkan-Nya
untuk percaya, meskipun hati itu keras. Sebaliknya, menurut keputusan yang sama,
orang yang tidak terpilih dibiarkan-Nya dalam kejahatan dan kekerasan hati
mereka sesuai dengan hukuman-Nya yang adil. Terutama di sinilah muncul di depan
kita pembedaan yang tak terselami, yang penuh kemurahan dan sekaligus adil itu,
yaitu pembedaan antara manusia yang telah sama-sama binasa, ataupun keputusan
Pemilihan dan Penolakan, yang dinyatakan dalam Firman Allah. Oleh orang yang
jahat, cemar, dan kurang mantap hal itu diputarbalikkan sehingga mereka binasa,
tetapi bagi jiwa orang kudus dan yang takut akan Allah hal ini menyediakan
hiburan yang tak terkatakan.

. Pemilihan ini adalah rencana Allah yang tak berubah-ubah. Olehnya, sebelum
dunia dijadikan, dipilih-Nya sejumlah orang dari segenap umat manusia yang
karena kesalahannya sendiri kehilangan keutuhan yang semula dan jatuh ke dalam
dosa dan kebinasaan itu, agar mereka memperoleh keselamatan. Orang yang dipilih
itu tidak lebih baik atau lebih layak daripada orang lain, tetapi bersama dengan
yang lain itu tergeletak dalam sengsara. Maka pemilihan mereka terjadi menurut
perkenan kehendak-Nya yang sama sekali bebas, hanya karena kasih karunia saja,
dan berlangsung di dalam Kristus, yang telah ditentukan-Nya dari kekal untuk
menjadi Pengantara dan Kepala semua orang pilihan serta dasar keselamatan. Dan
agar mereka diselamatkan oleh Kristus, maka Allah memutuskan juga untuk
memberikan orang-orang pilihan itu kepada-Nya dan untuk memanggil serta menarik
mereka dengan ampuh oleh Firman dan Roh-Nya pada persekutuan dengan-Nya. Atau,
dengan perkataan lain, Allah telah memutuskan untuk mengaruniakan kepada mereka
iman yang sejati kepada Kristus, membenarkan dan menguduskan mereka, dan
akhirnya memuliakan mereka, setelah mereka tetap dipelihara dengan kuasa dalam
persekutuan Anak-Nya. Semua itu dilakukan-Nya untuk menyatakan rahmat-Nya dan
supaya terpujilah kekayaan kasih karunia-Nya yang mulia. Seperti tertulis,
'Sebab Allah telah memilih kita di dalam Kristus sebelum dunia dijadikan, supaya
kita kudus dan tak bercacat di hadapan-Nya dalam kasih. Melalui Yesus Kristus,
Dia telah menentukan kita dari semula untuk menjadi anak-anak bagi diri-Nya,
menurut perkenan kehendak-Nya, supaya terpujilah kasih karunia-Nya yang mulia,
yang dikaruniakan-Nya kepada kita di dalam Dia, yang dikasihi-Nya.' (Efe 1:4-6).
Dan di tempat lain, 'Dan mereka yang ditentukan-Nya dari semula, mereka itu juga
dipanggil-Nya. Dan mereka yang dipanggil-Nya, mereka itu juga dibenarkan-Nya.
Dan mereka yang dibenarkan-Nya, mereka itu juga dimuliakan-Nya.' (Rom 8:30).

. Pemilihan ini bukan bermacam-macam, melainkan satu dan sama dalam hal semua
orang yang hendak diselamatkan, baik dalam Perjanjian Lama maupun dalam
Perjanjian Baru. Karena Alkitab memang memberitakan kepada kita satu perkenan,
satu maksud, dan satu keputusan kehendak Allah. Olehnya kita telah dipilih-Nya
dari kekekalan untuk menerima baik kasih karunia maupun kemuliaan, baik
keselamatan maupun jalan keselamatan yang telah dipersiapkan-Nya supaya kita
berjalan di dalamnya (Efe 1:4-5 dan Efe 2:10).

. Pemilihan tersebut telah terjadi, bukan berdasarkan iman dan ketaatan iman,
kesucian ataupun sifat dan pembawaan lain yang baik yang mana pun, yang telah
tampak terlebih dahulu, seakan-akan hal-hal itu menjadi sebab atau syarat yang
seharusnya terdapat dalam diri manusia yang bakal dipilih, melainkan supaya
menghasilkan iman, ketaatan iman, kekudusan, dan seterusnya. Maka pemilihan itu
adalah sumber segala hal yang menyelamatkan. Sebagai hasil dan akibatnya
mengalirkan darinya iman, kekudusan dan karunia-karunia lain yang membawa
keselamatan, dan akhirnya kehidupan kekal sendiri. Hal ini sesuai dengan
kesaksian Sang Rasul, 'Dia telah memilih kita' (bukan: sebab kita sudah kudus
dan tak bercacat, melainkan) 'supaya kita kudus dan tak bercacat di
hadapan-Nya.' (Efe 1:4).

. Yang menjadi alasan pemilihan yang hanya berdasarkan rahmat ini hanyalah
perkenan Allah. Perkenan ini bukanlah keputusan untuk memilih, dari semua syarat
yang dapat diberlakukan, sifat atau perbuatan manusia yang tertentu menjadi
syarat keselamatan. Sebaliknya, perkenan ini adalah keputusan untuk mengangkat
orang-orang tertentu dari massa orang berdosa menjadi milik-Nya. Seperti
tertulis, 'Waktu anak-anak itu belum dilahirkan dan belum melakukan yang baik
atau yang jahat (...) dikatakan kepada Ribka: Anak yang tua akan menjadi hamba
anak yang muda, seperti tertulis, 'Aku mengasihi Yakub, tetapi membenci Esau.'
(Rom 9:11-13). Dan, 'Semua orang yang ditentukan Allah untuk hidup yang kekal,
menjadi percaya.' (Kis 13:48).

. Sebagaimana Allah sendiri berhikmat sempurna, tidak berubah-ubah, maha
mengetahui, dan mahakuasa, begitu pula pemilihan yang dilakukan-Nya tidak dapat
ditiadakan dan dilakukan ulang, diubah, dibatalkan atau diputus, dan tidak
mungkin juga orang-orang pilihan ditolak atau jumlah mereka dikurangi.

. Orang-orang pilihan diyakinkan mengenai pemilihan mereka yang kekal dan yang
tak berubah-ubah, yaitu pemilihan untuk menerima keselamatan. Mereka diyakinkan
tentangnya masing-masing pada waktunya, walau tingkatnya berbeda-beda dan
kadarnya tidak sama. Keyakinan ini tidak didapatkan orang pilihan dengan cara
mengusut hal-hal yang tersembunyi dan rahasia-rahasia Allah yang dalam. Tetapi
mereka mendapatkannya dengan mengamati pada diri mereka sendiri dengan
kegembiraan rohani dan sukacita yang kudus berbagai hal yang dapat disangkal
merupakan buah pemilihan dan yang ditunjukkan dalam Firman Allah, seperti
umpamanya iman yang sejati kepada Kristus, takut akan Allah bagaikan seorang
anak, dukacita menurut kehendak Allah karena dosa, lapar, dan haus akan
kebenaran, dan seterusnya.

. Kesadaran dan keyakinan akan pemilihan itu menyebabkan anak-anak Allah makin
hari makin bertambah merendahkan diri di hadapan Allah, menyembah jurang
kemurahan-Nya, menyucikan diri, dan membalas kasih Dia yang telah begitu
mengasihi-Nya dengan kasih yang menyala-nyala. Maka ajaran pemilihan itu dan
perenungan tentangnya sama sekali tidak membuat mereka menjadi malas
melaksanakan perintah-perintah Allah, atau berlengah-lengah secara daging. Hal
itu, menurut hukuman Allah yang adil, biasa dialami orang yang memang dengan
gegabah menganggap dirinya sudah memiliki dirinya sudah memiliki anugerah
pemilihan, ataupun berkhayal tentangnya dengan seenaknya dan lancang, namun
tidak mau mengikuti jejak orang pilihan.

. Menurut rencana Allah yang penuh hikmat, ajaran tentang pemilihan ilahi itu
telah diberitakan oleh para Nabi, oleh Kristus sendiri, dan oleh para Rasul,
baik dalam Perjanjian Lama maupun dalam Perjanjian Baru, dan sesudah itu
dituliskan dan diwariskan di dalam Kitab-kitab Suci. Begitu pula, ajaran itu
harus dikemukakan juga pada masa kini, pada saat dan tempat yang tepat, dalam
gereja Allah, yang memang secara khusus menjadi tempat tujuannya. Hal itu
hendaknya dilakukan dengan kemampuan membedakan, dengan takwa dan kudus, tanpa
mengusut jalan-jalan Yang Mahatinggi, demi kemuliaan Nama Allah yang mahakudus
dan demi penghiburan yang menggairahkan bagi umat-Nya.

. Anugerah pemilihan kita, yang abadi dan yang dikaruniakan dengan cuma-cuma,
terutama ditunjukkan dan dianjurkan kepada kita oleh Kitab Suci ketika
disaksikan selanjutnya, bahwa tidak semua orang dipilih. Ada yang tidak dipilih
atau dilewatkan Allah dalam pemilihan-Nya yang kekal. Tentang mereka Allah telah
memutuskan, menurut perkenan-Nya yang sama sekali bebas, adil, tak bercacat, dan
tidak berubah-ubah, untuk membiarkan mereka dalam sengsara bersama, tempat
mereka telah menjatuhkan diri oleh kesalahan mereka sendiri, dan untuk tidak
mengaruniakan kepada mereka iman yang menyelamatkan dan karunia pertobatan,
malah untuk membiarkan mereka di jalan-jalan mereka sendiri dan di bawah
hukuman-Nya yang adil, dan untuk akhirnya menghakimi mereka dan menjatuhkan
hukuman yang kekal atas mereka, bukan hanya karena ketidakpercayaan mereka,
melainkan juga karena semua dosanya yang lain, supaya dengan demikian
diperlihatkan-Nya keadilan-Nya. Inilah keputusan penolakan, yang tidak
menjadikan Allah Penyebab dosa - pikiran itu hujat! - tetapi menetapkan Dia
selaku Hakim dan Pembalas dosa yang dahsyat, tak bercacat, dan adil.

. Ada orang yang belum merasakan dengan ampuh dalam dirinya iman yang hidup
kepada Kristus atau keyakinan hati yang teguh, kedamaian hati nurani,
pelaksanaan ketaatan bagaikan seorang anak, dan hal bermegah dalam Allah oleh
Kristus, meskipun mereka memakai segala sarana yang, menurut janji Allah,
dipakai-Nya untuk mengerjakan semua itu di dalam diri kita. Akan tetapi,
janganlah hati mereka menjadi tawar, bila mereka mendengar orang berbicara
tentang penolakan, dan janganlah mereka menganggap diri termasuk orang-orang
yang ditolak. Sebaliknya, hendaklah mereka tetap memakai sarana-sarana itu
dengan rajin, sangat merindukan saat karunia akan dianugerahkan dengan lebih
berlimpah, dan menantikannya dengan penuh hormat serta rendah hati. Apalagi
mereka yang sungguh ingin bertobat kepada Allah, yang hanya mau berkenan
kepada-Nya saja, dan ingin dilepaskan dari tubuh maut ini, namun belum dapat
maju di jalan kesalehan dan iman sejauh mereka kehendaki, mereka tidak usah
merasa takut berhadapan dengan ajaran penolakan ini. Karena Allah yang penuh
belas kasihan telah berjanji, bahwa sumbu yang pudar nyalanya tidak akan
dipadamkan-Nya dan buluh yang patah terkulai tidak akan diputuskan-Nya. Akan
tetapi, ajaran ini dengan selayaknya menakutkan mereka yang tidak mempedulikan
Allah dan Kristus Sang Juruselamat, dan yang seluruhnya mengabdi kepada
urusan-urusan dunia ini serta kepada hawa nafsu daging - setidak-tidaknya selama
mereka tidak bertobat dengan sungguh-sungguh kepada Allah.

. Tentang kehendak Allah harus kita tentukan pendapat hanya berdasarkan Firman-Nya sendiri. Firman itu menyaksikan kepada kita, bahwa anak-anak orang percaya adalah kudus, bukan karena kodrat mereka, melainkan karena perjanjian rahmat yang mencakup mereka bersama orangtua mereka. Maka orangtua yang saleh tidak perlu bimbang tentang pemilihan dan keselamatan anak-anak mereka yang diambil Allah dari hidup ini pada masa mereka masih kanak-kanak.

. Kepada mereka yang bersungut-sungut karena anugerah pemilihan yang hanya berdasarkan rahmat, dan karena kekerasan penolakan yang adil, kita hadapkan perkataan rasul ini, 'Siapakah kamu, hai manusia, maka kamu membantah Allah?' (Rom 9:20). Dan perkataan ini dari Juruselamat kita, 'Tidakkah Aku bebas mempergunakan milik-Ku menurut kehendak hati-Ku?' (Mat 20:15). Sebaliknya, kita menyembah rahasia-rahasia keselamatan ini dengan takwa dan berseru bersama rasul, 'O, alangkah dalamnya kekayaan hikmat dan pengetahuan Allah! Sungguh tak terselidiki keputusan-keputusan-Nya dan sungguh tak terselami jalan-jalan-Nya! Sebab, siapakah yang mengetahui pikiran Tuhan? Atau siapakah yang mengetahui pikiran Tuhan? Atau siapakah yang pernah menjadi penasehat-Nya? Atau siapakah yang pernah memberikan sesuatu kepada-Nya, sehingga Dia harus menggantikannya? Sebab segala sesuatu adalah dari Dia, dan oleh Dia, dan kepada Dia: bagi Dialah kemuliaan sampai selama-lamanya! Amin.' (Rom 11:33-36).

*Penolakan ajaran sesat yang telah mengacaukan Gereja-gereja Belanda selama beberapa waktu*

Setelah menguraikan ajaran ortodoks mengenai pemilihan dan penolakan, sinode menolak ajaran-ajaran sesat orang yang mengajar sebagai berikut:

. Allah berkehendak menyelamatkan mereka yang bakal beriman dan bertekun dalam iman serta ketaatan iman itu; hanya itulah isi keputusan pemilihan untuk menerima keselamatan, dan dalam Firman Allah tidak dinyatakan sesuatu apa pun yang lain tentang keputusan itu.
Mereka ini menyesatkan orang-orang bersahaja dan nyata-nyata membantah Kitab Suci, yang menyaksikan bahwa Allah tidak hanya berkehendak menyelamatkan mereka yang bakal beriman, tetapi juga telah memilih dari kekekalan sejumlah orang yang tertentu. Kepada mereka ini, berbeda dengan orang lain, hendak dikaruniakan-Nya dalam hidup ini iman kepada Kristus dan ketekunan dalam iman itu. Seperti tertulis, 'Aku telah menyatakan nama-Mu kepada semua orang, yang Engkau berikan kepada-Ku dari dunia.' (Yoh 17:6). Dan, 'Semua orang yang ditentukan Allah untuk hidup yang kekal, menjadi percaya.' (Kis 13:48). Dan, 'Sebab di dalam Dia Allah telah memilih kita sebelum dunia dijadikan, supaya kita kudus dan tak bercacat di hadapan-Nya' dan seterusnya (Efe 1:4).

. Pemilihan oleh Allah untuk hidup yang kekal adalah bermacam-macam. Ada pemilihan yang umum dan tidak tentu, ada yang khusus dan tentu. Pemilihan yang disebut terakhir ini ada yang tidak tuntas, dapat dicabut, tidak bersifat menentukan, dan bersyarat, ada yang tuntas, tak dapat dicabut, bersifat menentukan, dan mutlak. Begitu pula: ada pemilihan untuk iman, ada pemilihan untuk keselamatan, sedemikian rupa hingga pemilihan untuk iman yang membenarkan tidak perlu disertai pemilihan yang bersifat menentukan untuk keselamatan.
Ajaran ini merupakan khayalan otak manusia, yang direka-reka di luar Alkitab. Olehnya ajaran mengenai pemilihan dirusak dan diputuskanlah rantai emas keselamatan kita ini, 'Mereka yang ditentukan-Nya dari semula, mereka itu juga dipanggil-Nya. Dan mereka yang dipanggil-Nya, mereka itu juga dibenarkan-Nya. Dan mereka yang dibenarkan-Nya, mereka itu juga dimuliakan-Nya.' (Rom 8:30).

. Isi perkenan dan rencana Allah, yang disebut-sebut oleh Alkitab dalam ajarannya tentang pemilihan, bukanlah bahwa Allah telah memilih sejumlah orang yang tertentu dengan tidak memilih orang lain. Sebaliknya, dari semua syarat yang dapat berlaku (di antaranya juga perbuatan hukum Taurat), ataupun dari segala hal ihwal yang ada, Allah telah memilih perbuatan iman, yang pada hakikatnya tidak berjasa, dan ketaatan iman yang tidak sempurna, menjadi syarat keselamatan. Ketaatan yang tidak sempurna itu dengan penuh kerahiman mau dinilai sempurna dan layak diupahi hidup yang kekal.
Ajaran sesat yang merusak ini menyebabkan perkenan Allah dan jasa Kristus hilang kekuatannya, dan membuat hati orang menyimpang, oleh pertanyaan-pertanyaan yang sia-sia, dari kebenaran yaitu pembenaran hanya berdasarkan rahmat, dan dari ajaran Alkitab yang sederhana. Lagi pula olehnya rasul dituduh berdusta, apabila ia berkata, 'Allah telah memanggil kita dengan panggilan kudus, bukan berdasarkan perbuatan kita, melainkan berdasarkan rencana dan kasih karunia-Nya sendiri, yang telah dianugerahkan kepada kita dalam Yesus Kristus sebelum permulaan zaman' (2Ti 1:9).

. Dalam pemilihan untuk iman, manusia harus memenuhi lebih dahulu syarat yang berikut: ia harus memakai dengan baik cahaya alamiah, dan harus saleh, sederhana, rendah hati, serta layak untuk hidup yang kekal, seolah-olah pemilihan bergantung sedikit pun pada hal-hal itu.
Mereka ini serupa benar dengan Pelagius dan bertentangan dengan ajaran Rasul yang menulis, 'Sebenarnya dahulu kami semua juga terhitung di antara mereka, ketika kami hidup di dalam hawa nafsu daging dan menuruti kehendak daging dan pikiran kami yang jahat. Pada dasarnya kami adalah orang-orang yang harus dimurkai, sama seperti mereka yang lain. Tetapi Allah yang kaya dengan rahmat, oleh karena kasih-Nya yang besar, yang dilimpahkan-Nya kepada kita, telah menghidupkan kita bersama-sama dengan Kristus, sekalipun kita telah mati oleh kesalahan-kesalahan kita - oleh kasih karunia kamu diselamatkan - dan di dalam Kristus Yesus Dia telah membangkitkan kita juga dan memberikan tempat bersama-sama dengan Dia di surga, supaya pada masa yang akan datang Dia menunjukkan kepada kita kekayaan kasih karunia-Nya, yang melimpah-limpah sesuai dengan kebaikan-Nya terhadap kita dalam Kristus Yesus. Sebab karena kasih karunia kamu diselamatkan oleh iman; itu bukan hasil usahamu, tetapi pemberian Allah, itu bukan hasil pekerjaanmu: jangan ada orang yang memegahkan diri' (Efe 2:3-9).

. Pemilihan orang-orang tertentu untuk keselamatan, yaitu pemilihan yang tidak tuntas dan tidak bersifat menentukan telah terjadi berdasarkan iman, pertobatan, hidup suci dan saleh yang baru mulai ataupun telah berlangsung beberapa lama, dan yang sudah tampak terlebih dahulu. Sebaliknya, pemilihan yang tuntas dan bersifat menentukan berdasarkan ketekunan sampai akhir iman, pertobatan, hidup suci dan saleh yang sudah tampak terlebih dahulu itu. Inilah 'kelayakan yang penuh rahmat dan Injili', yang menyebabkan orang yang dipilih lebih layak daripada orang yang tidak dipilih. Itulah sebabnya iman, ketaatan iman, hidup suci dan saleh, serta ketekunan tidak merupakan hasil pemilihan yang tidak berubah-ubah untuk kemuliaan, tetapi menjadi syarat-syarat dan penyebab-penyebabnya. Syarat-syarat itu telah ditentukan lebih dahulu, dan sudah tampak lebih dahulu bahwa orang-orang yang bakal dipilih secara tuntas akan memenuhinya, dan tanpa penyebab-penyebab itu pemilihan yang tak berubah-ubah untuk kemuliaan tidak terjadi.
+
Hal ini bertentangan dengan seluruh Alkitab, yang terus-menerus menegaskan perkataan ini dan lain sebagainya dalam telinga dan hati kita, 'Pemilihan bukanlah berdasarkan perbuatan, melainkan dari Dia yang memanggil' (Rom 9:11). 'Dan semua orang yang ditentukan Allah untuk hidup yang kekal, menjadi percaya' (Kis 13:48). 'Sebab di dalam Dia Allah telah memilih kita sebelum dunia dijadikan, supaya kita kudus' (Efe 1:4). 'Bukan kamu yang memilih Aku, tetapi Akulah yang memilih kamu' (Yoh 15:16). 'Tetapi jika hal itu terjadi karena kasih karunia, maka bukan lagi karena perbuatan' (Rom 11:6). 'Inilah kasih itu: Bukan kita yang telah mengasihi Allah, tetapi Allah yang telah mengasihi kita dan yang telah mengutus Anak-Nya' (1Yo 4:10).

. Pemilihan untuk keselamatan tidak selalu bersifat tidak berubah-ubah. Sebaliknya, ada orang pilihan yang dapat binasa dan juga betul-betul binasa untuk selama-lamanya, meskipun ada keputusan Allah.
Melalui kesesatan kasar ini mereka menjadikan Allah sebagai Allah yang berubah-ubah dan menumbangkan hiburan yang diambil oleh orang saleh dari kepastian pemilihan mereka. Pun mereka menentang Kitab-kitab Suci, yang mengajar bahwa 'orang-orang pilihan tidak disesatkan' (Mat 24:24); bahwa 'Kristus tidak mungkin kehilangan mereka yang diberikan Bapa kepada-Nya' (Yoh 6:39); bahwa 'mereka yang ditentukan, dipanggil, dan dibenarkan Allah dari semula, juga dimuliakan-Nya' (Rom 8:30).

. Di dalam kehidupan ini tidak ada buah pemilihan yang tidak berubah-ubah untuk kemuliaan dan tidak ada kesadaran tentangnya. Juga tidak ada kepastian tentangnya selain yang berdasarkan syarat yang berubah-ubah dan yang tidak pasti.
+
Tidak masuk akal menetapkan kepastian yang tidak pasti, lagi pula hal ini juga bertentangan dengan pengalaman orang kudus, yang berdasarkan kesadaran tentang pemilihan mereka bergembira bersama Rasul dan memuji-muji anugerah Allah itu (Efe 1). Sesuai dengan nasihat Kristus, mereka bersukacita bersama murid-murid-Nya, karena nama mereka terdaftar di surga (Luk 10:20).
+
Juga, mereka menjadikan kesadaran tentang pemilihan mereka itu sebagai penahan panah api godaan-godaan iblis, sambil bertanya, 'Siapakah yang akan menggugat orang-orang pilihan Allah?' (Rom 8:33).

. Allah tidak pernah memutuskan, hanya berdasarkan kehendak-Nya yang adil semata-mata, untuk membiarkan seseorang dalam kejatuhan Adam dan dalam keadaan dosa serta hukuman yang berlaku umum, ataupun untuk melewatkan seseorang dalam pembagian anugerah yang diperlukan untuk iman dan pertobatan.
+
Sebab, yang ini sudah pasti, 'Dia menaruh belas kasihan kepada siapa yang dikehendaki-Nya dan Dia menegarkan hati siapa yang dikehendaki-Nya' (Rom 9:18). Juga, 'Kepadamu diberi karunia untuk mengetahui rahasia Kerajaan Surga, tetapi kepada mereka tidak' (Mat 13:11). Demikian pula, 'Aku bersyukur kepada-Mu, Bapa, Tuhan langit dan bumi, karena semuanya itu Engkau sembunyikan bagi orang bijak dan orang pandai, tetapi Engkau nyatakan kepada orang kecil. Ya Bapa, itulah yang berkenan kepada-Mu' (Mat 11:25,26).

. Alasan yang menyebabkan Allah mengalamatkan Injil kepada bangsa yang satu alih-alih kepada bangsa yang lain, bukan hanya perkenan Allah semata-mata, melainkan karena bangsa yang satu lebih baik dan lebih layak daripada bangsa lain, yang tidak mendapat bagian dalam Injil.
+
Hal ini disangkal Musa, waktu ia berkata kepada bangsa Israel demikian, 'Sesungguhnya, TUHAN, Allahmulah yang empunya langit, bahkan langit yang mengatasi segala langit, dan bumi dengan segala isinya; tetapi hanya oleh nenek moyangmulah hati TUHAN terpikat, sehingga Dia mengasihi mereka, dan keturunan merekalah, yakni kamu, yang dipilih-Nya dari segala bangsa, seperti sekarang ini.' (Ula 10:14-15). Dan Kristus berkata, 'Celakalah engkau Khorazim! Celakalah engkau Betsaida! Karena jika di Tirus dan Sidon terjadi mukjizat-mukjizat yang telah terjadi di tengah-tengah kamu, sudah lama mereka bertobat dan berkabung.' (Mat 11:21).

== II. Kematian Kristus dan penebusan manusia olehnya

. Allah tidak hanya mahamurah, tetapi juga mahaadil. Maka keadilan-Nya itu - demikian Dia telah menyatakan diri dalam Firman-Nya - menuntut agar dosa-dosa yang telah kita perbuat terhadap keagungan-Nya yang tak terhingga itu mendapat hukuman-hukuman itu, kecuali jika tuntutan-tuntutan keadilan Allah dipenuhi.

. Tetapi karena kita sendiri tidak sanggup menyediakan pelunasan dan melepaskan diri kita dari murka Allah, maka karena kasih-Nya yang tak terhingga Allah telah mengaruniakan Anak-Nya yang tunggal menjadi jaminan bagi kita. Dia telah menjadi dosa dan kutuk di atas kayu salib karena kita dan sebagai ganti kita, untuk menyediakan pelunasan bagi kita.

. Kematian Anak Allah ini adalah korban dan pelunasan yang satu-satunya dan sempurna untuk dosa. Kematian itu tidak terbatas kekuatan dan nilainya dan lebih dari cukup untuk mendamaikan dosa seluruh dunia.

. Kematian ini demikian kuat dan bernilai, karena Pribadi yang telah mengalaminya itu bukan hanya manusia sejati dan benar-benar kudus, melainkan juga Anak Allah yang tunggal, yang se-Zat dengan Bapa dan Roh Kudus dan bersama-sama Mereka kekal dan tak terhingga sebagaimana seharusnya Dia yang menjadi Juruselamat kita. Tambahan lagi, karena kematian-Nya disertai kesadaran akan murka Allah dan akan kutuk yang patut menimpa kita karena dosa-dosa kita.

. Selanjutnya janji Injil ialah, bahwa setiap orang yang percaya kepada Kristus yang disalibkan itu tidak binasa, tetapi beroleh hidup yang kekal. Janji itu harus diberitakan dan dimaklumkan kepada semua bangsa dan semua orang yang menurut perkenan Allah, menjadi alamat pemberitaan Injil-Nya, disertai perintah bertobat dan percaya, tanpa mengadakan pembedaan.

. Banyak orang yang dipanggil oleh Injil, tidak bertobat dan tidak percaya kepada Kristus. Sebaliknya, mereka binasa dalam ketidakpercayaan. Akan tetapi, hal ini tidak terjadi oleh sebab korban Kristus di atas kayu salib bercacat atau berkekurangan, tetapi lantaran kesalahan mereka sendiri.

. Akan tetapi, semua orang yang sungguh-sungguh percaya, dan oleh kematian Kristus dibebaskan dan diselamatkan dari dosa serta kebinasaan, menikmati anugerah ini hanya berdasarkan rahmat Allah. Rahmat itu dianugerahkan kepada mereka dari kekekalan, di dalam Kristus, walaupun Allah tidak berkeharusan menganugerahkannya kepada seorang pun.

. Sebab inilah keputusan yang berdaulat, kehendak yang penuh rahmat, dan maksud Allah Bapa, yaitu agar keampuhan yang menghidupkan dan menyelamatkan yang terdapat dalam kematian Anak-Nya yang amat berharga itu menjangkau semua orang terpilih, untuk mengaruniakan hanya kepada mereka saja iman yang membenarkan, dan oleh iman itu dengan tak tergagalkan mengantarkan mereka kepada keselamatan. Dengan perkataan lain: Allah telah menghendaki agar Kristus, oleh penumpahan darah-Nya di atas salib (yang olehnya perjanjian baru telah diteguhkan-Nya), dari antara segala bangsa dan suku dan kaum dan bahasa menebus dengan ampuh semua orang - dan hanya mereka itu saja - yang dari kekekalan sudah terpilih untuk keselamatan dan yang telah diberikan Bapa kepada-Nya. Begitu pula, agar Kristus mengaruniakan kepada mereka iman, yang telah diperoleh-Nya bagi mereka oleh kematian-Nya, sama seperti karunia-karunia Roh Kudus yang lain yang membawa keselamatan. Begitu pula, agar Dia menyucikan mereka dengan darah-Nya dari semua dosa mereka, baik dari dosa bawaan maupun dari dosa-dosa yang nyata, yang mereka lakukan sebelum atau sesudah menjadi percaya, dan agar Dia memelihara mereka dengan setia sampai akhir, dan pada kesudahannya menempatkan mereka di hadapan diri-Nya dengan penuh kemuliaan, tanpa cacat atau kerut.

. Keputusan ini, yang berasal dari kasih Allah yang abadi terhadap orang pilihan, telah digenapi secara kuat sejak awal dunia hingga dewasa ini, dan alam maut pun tidak berhasil melawannya. Keputusan itu akan digenapi juga untuk seterusnya, sedemikian rupa, hingga orang pilihan, masing-masing pada zamannya, akan dihimpun menjadi satu kumpulan, dan selalu akan ada Gereja orang-orang percaya, yang berdasarkan darah Kristus. Gereja itu tetap mengasihi Dia, Juruselamatnya, yang telah menyerahkan nyawa-Nya baginya di atas kayu salib, sama seperti seorang mempelai laki-laki menyerahkan nyawanya bagi mempelai perempuannya, bertekun beribadah kepada-Nya, dan memuji-muji Dia sekarang dan sampai selama-lamanya. Amin.

*Penolakan ajaran sesat*

Setelah menguraikan ajaran ortodoks maka sinode menolak ajaran-ajaran sesat orang yang mengajar sebagai berikut:

. Allah Bapa telah menentukan Anak-Nya untuk mati di atas kayu salib tanpa adanya keputusan yang pasti dan tentu untuk menyelamatkan orang-orang tertentu. Malahan, andaipun penebusan yang diperoleh itu tidak pernah menjadi milik nyata satu orang pun, namun perlunya, manfaat, dan nilai yang tercantum di dalam apa yang diperoleh melalui kematian Kristus itu dapat saja tetap berlaku lengkap dan tetap tinggal sempurna, genap, dan utuh dalam semua bagiannya.
+
Ajaran ini adalah penghinaan terhadap hikmat Bapa dan jasa Yesus Kristus, dan bertentangan dengan Alkitab. Karena Juruselamat kita berkata, "Aku memberikan nyawa-Ku bagi domba-domba-Ku dan Aku mengenal mereka" (Yoh 10:15,27). Dan Nabi Yesaya berkata mengenai Juruselamat, "Apabila ia menyerahkan dirinya sebagai korban penebus salah, ia akan melihat keturunannya, umurnya akan lanjut, dan kehendak TUHAN akan terlaksana olehnya" (Yes 53:10). Akhirnya ajaran ini menumbangkan pasal pengakuan iman yang mengandung kepercayaan kita akan "Gereja Kristen yang am".

. Maksud kematian Kristus bukanlah agar perjanjian baru, yaitu perjanjian rahmat, sungguh-sungguh diteguhkan-Nya oleh darah-Nya, melainkan semata-mata agar bagi Bapa diperoleh-Nya hak untuk sekali lagi mengadakan perjanjian dengan manusia, entah perjanjian rahmat entah perjanjian perbuatan, sebagaimana dikehendaki Bapa.
+
Ajaran ini bertentangan dengan Alkitab, yang mengajar bahwa Kristus telah menjadi Jaminan dan Pengantara perjanjian yang lebih baik, yaitu perjanjian baru, dan bahwa surat wasiat barulah sah, bila pembuat wasiat itu telah mati.

. Oleh pelunasan yang telah dilakukan-Nya, Kristus tidak memperoleh dengan pasti bagi seorang pun baik keselamatan sendiri maupun iman yang membuat pelunasan itu dengan ampuh diraih demi keselamatan. Sebaliknya, Dia hanya memperoleh bagi Bapa kuasa atau kemauan yang bulat untuk membuka babak baru dalam tindakannya terhadap manusia dan menentukan syarat-syarat baru apa saja yang dikehendaki-Nya. Apakah syarat-syarat itu dipenuhi, tergantung pada kehendak bebas manusia. Maka dapat saja terjadi, bahwa tidak seorang pun, ataupun semua orang memenuhinya.
+
Mereka ini meremehkan kematian Kristus, sama sekali tidak mengakui buah atau anugerah utama yang diperoleh melalui kematian itu, dan memanggil ajaran sesat Pelagius kembali dari neraka.

. Isi perjanjian baru, yaitu perjanjian rahmat, yang telah diikat oleh Allah Bapa dengan manusia melalui kematian Kristus, bukanlah bahwa kita dibenarkan di hadapan Allah dan diselamatkan oleh iman sejauh iman ini meraih jasa Kristus. Sebaliknya, isinya bahwa Allah membatalkan tuntutan ketaatan sempurna terhadap hukum Taurat dan menganggap iman itu sendiri serta ketaatan iman, meskipun tidak sempurna, sebagai ketaatan sempurna kepada hukum Taurat serta dengan penuh rahmat menilainya layak diganjar hidup yang kekal.
+
Mereka ini membantah Alkitab, yang berkata, "Oleh kasih karunia mereka telah dibenarkan dengan cuma-cuma karena penebusan dalam Kristus Yesus. Kristus Yesus telah ditentukan Allah menjadi jalan pendamaian karena iman, dalam darah-Nya (Rom 3:24-25). Bersama Socinus yang fasik itu mereka memasukkan ajaran yang baru dan asing tentang pembenaran manusia di hadapan Allah, yang bertentangan dengan perasaan bulat seluruh gereja.

. Semua orang telah diterima oleh Allah, sehingga mereka diperdamaikan dengan Allah dan turut mengambil bagian dalam karunia perjanjian itu. Maka tidak seorang pun takluk pada hukuman kekal karena dosa turunan, dan tidak seorang pun akan dihukum karenanya. Sebaliknya, semua orang bebas dari kesalahan yang disebabkan dosa tersebut.
+
Pandangan ini bertentangan dengan Alkitab, yang menegaskan, bahwa "pada dasarnya kita adalah orang-orang yang harus dimurkai" (Efe 2:3).

. Sejauh hal itu bergantung kepada Allah, Dia telah berkehendak mengaruniakan secara sama rata kepada semua orang anugerah-anugerah yang telah diperoleh oleh kematian Kristus. Jikalau ada orang yang mendapat bagian dalam pengampunan dosa dan hidup yang kekal sedangkan yang lain tidak, maka perbedaan itu bergantung pada kehendaknya yang bebas, yang meraih anugerah yang ditawarkan tanpa memandang bulu itu, bukan pada karunia khusus dari rahmat Allah, yang bekerja dalam orang itu dengan ampuh sehingga mereka memeluk kasih karunia itu, sedangkan yang lain tidak.
+
Mereka ini menyalahgunakan pembedaan antara hal memperoleh dan hal memeluk, untuk meresapkan pendapat tersebut ke dalam hati orang yang kurang hati-hati dan yang tidak berpengalaman. Mereka berbuat seolah-olah mereka mengemukakan pembedaan ini dalam arti yang sehat, namun mereka mencoba menyuguhkan kepada rakyat racun yang mematikan, yakni ajaran sesat kaum Pelagian.

. Kristus tidak dapat dan tidak perlu mati bagi mereka yang dikasihi Allah dengan kasih yang tertinggi dan yang telah dipilih-Nya untuk hidup yang kekal. Dia memang tidak mati bagi mereka, karena orang yang sedemikian tidak memerlukan kematian Kristus.
+
Mereka membantah Sang Rasul, yang berkata bahwa Kristus "telah mengasihi aku dan menyerahkan diri-Nya untuk aku" (Gal 2:20). Demikian juga, "Siapakah yang akan menggugat orang-orang pilihan Allah? Allah, yang membenarkan mereka? Siapakah yang akan menghukum mereka? Kristus Yesus, yang telah mati?", yaitu bagi mereka (Rom 8:33-34). Dan Juruselamat sendiri berkata, "Aku memberikan nyawa-Ku bagi domba-domba-Ku" (Yoh 10:15). Dan, "Inilah perintah-Ku, yaitu supaya kamu saling mengasihi, seperti Aku telah mengasihi kamu. Tidak ada kasih yang lebih besar daripada kasih seorang yang memberikan nyawanya untuk sahabat-sahabatnya" (Yoh 15:12-13).

== III, IV. Kerusakan manusia & Pertobatannya kepada Allah serta cara pertobatan itu

. Pada mulanya manusia diciptakan menurut gambar Allah dan diberi perlengkapan yang serba indah: dalam akal budinya terdapat pengetahuan yang benar dan menyelamatkan tentang Penciptanya serta tentang hal-hal rohani; dalam kehendak dan hatinya, kebenaran; dalam semua perasaan hatinya, kemurnian. Maka, ia sepenuhnya kudus. Tetapi oleh hasutan iblis dan kehendak bebasnya sendiri ia telah menyimpang dari Allah dan membuang karunia-karunia ulung itu. Dan sebagai gantinya manusia telah mendapatkan bagi dirinya: kebutaan, kegelapan yang mengerikan, pertimbangan yang bebal dan jahat dalam akal budinya; kekejian, pemberontakan, dan ketegaran dalam kehendak dan hatinya; lagi pula ketidakmurnian dalam perasaan hatinya.

. Sama seperti keadaan manusia setelah ia jatuh, demikian pula keadaan anak-anaknya; manusia yang rusak memperanakkan anak-anak yang rusak. Dengan cara ini menurut hukuman Allah yang adil kerusakan menjalar dari Adam kepada semua anak cucunya - kecuali Yesus - bukan karena peniruan, sebagaimana dulu telah dikatakan oleh kaum Pelagian, melainkan karena pembiakan kodrat yang rusak itu.

. Oleh karena itu, semua orang dikandung dalam dosa dan murka Allah sudah berada pada mereka saat mereka lahir. Mereka tidak sanggup berbuat kebaikan apa pun demi keselamatannya, tetapi mereka cenderung pada kejahatan, mereka mati di tengah dosa, dan menjadi hamba dosa. Mereka tidak mau dan tidak sanggup kembali kepada Allah dan membenahi kodrat mereka yang bejat ataupun menyiapkan diri untuk pembenahannya, tanpa karunia Roh Kudus yang melahirkan kembali.

. Memang, setelah manusia jatuh masih tinggal di dalamnya sisa terang kodrati. Berkat terang itu, ia tetap memiliki pengetahuan sedikit tentang Allah, tentang alam dunia, tentang perbedaan antara apa yang bersusila dan yang aib, dan tampak berupaya seadanya untuk mengejar kebajikan serta ketertiban lahiriah. Akan tetapi, jangankan oleh terang kodrati itu memperoleh pengenalan yang menyelamatkan tentang Allah dan menjadi sanggup bertobat kepada-Nya, menggunakan terang itu dengan tepat dalam kehidupan sehari-hari dan dalam urusan-urusan kemasyarakatan pun manusia tidak bisa.
+
Bahkan, ia mengaburkan terang itu - bagaimanapun juga sifat terang ini - dengan berbagai cara dan menindasnya dalam kelaliman. Karena ia berbuat begitu, maka ia sama sekali tidak dapat lagi berdalih di hadapan Allah.

. Apa yang berlaku terhadap terang kodrati itu, juga berlaku dalam hubungan ini terhadap hukum Kesepuluh Perintah yang diberikan Allah melalui Musa khususnya kepada orang Yahudi. Sebab hukum itu memang menyingkapkan kebesaran dosa dan makin lama makin meyakinkan manusia akan kesalahannya, tetapi menunjukkan obat penawarnya dan juga tidak memberikan kekuatan untuk luput dari sengsara itu. Karena hukum itu telah menjadi tidak berdaya oleh daging, dan membiarkan pelanggarnya tetap berada di bawah kutuk, maka tidak mungkin manusia memperoleh rahmat yang menyelamatkan melalui hukum itu.

. Maka apa yang tidak mungkin dilakukan oleh terang kodrati dan hukum Taurat, itulah yang dikerjakan Allah oleh kuasa Roh Kudus dan oleh Firman atau pelayanan pendamaian, yakni Injil Mesias. Allah telah berkenan menyelamatkan orang percaya baik pada zaman Perjanjian Lama maupun pada zaman Perjanjian Baru oleh Injil itu.

. Rahasia kehendak-Nya itu telah disingkapkan Allah kepada sejumlah kecil orang pada zaman Perjanjian Lama. Sebaliknya, pada zaman Perjanjian Baru (setelah perbedaan antara bangsa-bangsa ditiadakan) Allah telah menyatakannya kepada lebih banyak orang. Sebab perbedaan ini janganlah dicari dalam hal ini, bahwa bangsa yang satu lebih layak ataupun memanfaatkan terang kodrati dengan lebih baik dibandingkan bangsa lain, tetapi dalam perkenan Allah yang berdaulat dan dalam kasih-Nya yang diberikan secara cuma-cuma. Itulah sebabnya maka mereka yang dianugerahi karunia yang sedemikian besar - walaupun mereka sama sekali tidak layak menerimanya, bahkan berlawanan dengan semua yang patut mereka terima - harus mengakui karunia itu dengan rendah hati dan penuh syukur. Tetapi dalam hal orang-orang lain, yang tidak dianugerahi karunia itu, haruslah mereka bersama Sang Rasul menyembah kekerasan dan keadilan hukuman-hukuman Allah, dan sekali-kali tidak mengusut hukuman-hukuman itu.

. Akan tetapi, semua orang yang dipanggil oleh Injil, dipanggil dengan sungguh-sungguh. Sebab dalam firman-Nya Allah memperlihatkan sungguh-sungguh dan dengan sebenarnya apa yang berkenan kepada-Nya, yaitu bahwa mereka yang dipanggil itu datang kepada-Nya dan percaya dijanjikan-Nya kesentosaan jiwa dan hidup yang kekal.

. Banyak orang yang dipanggil oleh pelayanan Injil tidak datang dan tidak ditobatkan. Kesalahannya tidak dapat ditimpakan kepada Injil, atau kepada Kristus yang ditawarkan oleh Injil, dan tidak juga kepada Allah, yang memanggil orang melalui Injil dan bahkan memberikan berbagai karunia kepada mereka yang dipanggil-Nya. Kesalahannya terletak dalam diri mereka; ada yang memang menerimanya, tetapi tidak mengizinkannya masuk ke dalam hatinya, dan oleh sebab itu mundur lagi setelah sebentar bersukacita dalam iman yang sementara itu; ada yang menghimpit benih Firman di antara semak duri kekuatiran dan keriaan dunia dan tidak menghasilkan buah. Hal ini diajarkan Juruselamat kita dalam perumpamaan tentang benih.

. Orang-orang lain yang dipanggil oleh pelayanan Injil, datang dan ditobatkan. Hal itu jangan dipulangkan kepada manusia, seolah-olah kehendaknya yang bebas menyebabkan ia berbeda dari orang-orang lain, yang diperlengkapi karunia yang sama besar atau paling tidak cukup agar mereka percaya dan bertobat (seperti yang dinyatakan oleh kesesatan sombong Pelagius). Sebaliknya, hal itu harus dipulangkan kepada Allah. Sebagaimana sejak semula orang-orang kepunyaan-Nya telah dipilih-Nya dalam Kristus, demikian juga mereka dipanggil-Nya dengan ampuh dalam hidup ini. Dia mengaruniakan kepada mereka iman dan pertobatan, dan setelah melepaskan mereka dari kuasa kegelapan memindahkan mereka ke dalam kerajaan Anak-Nya. Maksud-Nya agar mereka memasyhurkan perbuatan-perbuatan besar Dia, yang telah memanggil mereka ke luar dari kegelapan kepada terang-Nya yang ajaib, dan supaya jangan mereka bermegah dalam diri mereka sendiri, melainkan di dalam Tuhan, seperti yang disaksikan kitab-kitab para Rasul di mana-mana.

. Akan tetapi, bilamana Allah melaksanakan perkenan-Nya itu di dalam orang pilihan, dan mengerjakan di dalam mereka pertobatan yang sejati, maka Dia telah hanya membuat Injil diberitakan kepada mereka dan tidak hanya menerangi pikiran mereka oleh Roh sedemikian kuat, hingga mereka memahami dengan baik dan menilai hal-hal yang berasal dari Roh Kudus. Dia bahkan juga masuk sampai ke dalam batin manusia dengan keampuhan Roh Kudus yang sama itu, yang mengerjakan kelahiran kembali; hati yang tertutup dibuka-Nya, apa yang keras dilunakkan-Nya, apa yang tidak bersunat disunati-Nya, dalam kehendak dituangkan-Nya sifat-sifat baru: kehendak yang tadinya mati dihidupkan-Nya, yang jahat dijadikan-Nya baik, yang tidak bersedia dijadikan-Nya bersedia, yang melawan dijadikan-Nya taat. Dia menggerakkan dan menguatkan kehendak sedemikian, hingga kehendak itu, seperti pohon yang baik, sanggup menghasilkan buah berupa perbuatan-perbuatan baik.

. Inilah kelahiran kembali, pembaruan, penciptaan baru, pembangkitan dari antara orang mati, dan karya menghidupkan, yang dimasyhurkan dalam Alkitab dan yang dikerjakan oleh Allah tanpa kita di dalam kita. Kelahiran kembali itu tidak terjadi dalam diri kita hanya melalui bunyi kata-kata pemberitaan, tidak juga oleh nasihat yang lemah lembut ataupun karya yang begitu rupa sehingga setelah Allah menyelesaikan karya itu maka manusia masih dapat menentukan apakah ia dilahirkan kembali atau tidak dan ditobatkan atau tidak. Sebaliknya, hal itu jelas merupakan karya adikodrati, yang amat kuat sekaligus amat lembut, ajaib, tersembunyi, dan tak terkatakan. Menurut kesaksian Alkitab (yang diilhami oleh Dia yang melakukan karya itu), daya karya itu tidak kalah besar dibandingkan dengan penciptaan atau pembangkitan orang mati. Olehnya semua orang yang hatinya menjadi tempat Allah bekerja dengan cara yang menakjubkan ini, pasti dilahirkan kembali dengan cara yang tak tergagalkan dan ampuh, serta benar-benar menjadi percaya. Lalu kehendak yang telah diperbarui itu tidak hanya digerakkan dan didorong Allah, tetapi setelah digerakkan Allah, maka kehendak itu sendiri juga bergerak. Oleh sebab itu, dikatakan juga dengan tepat bahwa, oleh karunia yang telah diterimanya, manusia sendiri percaya dan bertobat.

. Cara karya ini tidak dapat dipahami sepenuhnya oleh orang percaya selama hidup ini. Sementara itu mereka merasa tenteram karena mengetahui dan merasa, bahwa oleh karunia Allah itu mereka percaya dengan hati dan mengasihi Juruselamat mereka.

. Maka iman merupakan karunia Allah. Bukan karena iman itu ditawarkan Allah kepada manusia, agar manusia berbuat sekehendaknya, melainkan karena iman itu sesungguhnya diberikan, diilhamkan, dicurahkan kepada manusia. Bukan juga karena Allah hanya memberikan kemampuan untuk percaya, dan sesudah itu mengharapkan persetujuan atau percaya yang nyata dari kehendak manusia yang bebas, melainkan karena Dia yang mengerjakan baik kemauan maupun pekerjaan, bahkan mengerjakan semuanya di dalam semua orang, Dialah yang mengerjakan di dalam manusia baik kemauan untuk percaya maupun iman itu sendiri.

. Allah tidak berkeharusan memberikan karunia ini kepada seorang pun. Sebab, apakah keharusan-Nya kepada seseorang yang tidak dapat terlebih dahulu memberikan kepada-Nya sesuatu apa pun yang wajib diganjar? Tambahan lagi, apakah gerangan keharusan Allah kepada seseorang yang hanya memiliki dosa dan dusta? Jadi, barang siapa yang menerima karunia ini, hanya kepada Allah ia berhutang syukur. Barang siapa yang tidak menerima karunia ini, ia sama sekali acuh tak acuh akan perkara-perkara rohani ini dan bersenang-senang atas hal-hal kepunyaannya, ataupun karena merasa aman ia bermegah dengan tidak beralasan seakan-akan memiliki apa yang tidak dimilikinya. Namun, sesuai dengan teladan para Rasul, mereka yang mengaku imannya secara lahiriah dan yang membenahi hidupnya, harus dinilai dan disebut dengan sebaik-baiknya, sebab kita tidak mengenal lubuk hati manusia. Adapun orang lain, yang belum terpanggil, orang harus mendoakan mereka pada Allah, yang menjadikan apa yang tidak ada menjadi ada. Jangan sekali-kali kita berlaku sombong terhadap mereka, seolah-olah kita sendirilah yang menyebabkan kita berbeda dari mereka.

. Akan tetapi, manusia, meskipun ia telah jatuh ke dalam dosa, adalah tetap manusia, yang diperlengkapi akal dan kehendak. Dan dosa, yang telah menjalar kepada seluruh umat manusia, tidak memusnahkan kodrat manusia itu, tetapi merusakkannya dan mematikannya secara rohani. Begitu pula, karunia ilahi, yakni kelahiran kembali itu juga tidak bekerja di dalam manusia seolah-olah ia adalah sebongkah kayu dan sebuah batu, dan karunia itu tidak memusnahkan kehendak manusia dan sifat-sifat kehendak itu, dan tidak memaksa manusia berlawanan dengan kehendaknya. Tetapi karunia ilahi itu menghidupkan kehendak secara rohani, menyembuhkannya, memperbaikinya, dan menundukkannya secara lembut sekaligus kuat. Maka, di mana dahulu kedegilan dan perlawanan daging merajalela, sekarang oleh Roh mulai berkuasa ketaatan yang rela dan tulus. Itulah yang merupakan pembaruan dan kebebasan kehendak kita yang sejati dan rohani. Ya, jika Pembuat segala sesuatu yang baik, yang patut dikagumi itu, tidak bertindak sedemikian rupa terhadap kita, maka janganlah manusia berharap dapat bangkit dari kejatuhan melalui kehendaknya yang bebas, yang olehnya ia telah menceburkan diri ke dalam kebinasaan pada waktu ia masih berdiri.

. Karya Allah yang mahakuasa, yang olehnya Dia menciptakan hidup kodrati kita dan memeliharanya, tidak mencegah pemakaian sarana-sarana yang olehnya Allah dalam hikmat dan kebaikan-Nya yang tak terhingga ingin melaksanakan kekuatan-Nya itu, tetapi justru menuntut pemakaiannya. Demikian pula halnya karya adikodrati Allah yang tersebut di atas, yang olehnya kita dilahirkan-Nya kembali: karya ini sekali-kali tidak mencegah atau meniadakan pemakaian Injil yang telah ditentukan Allah yang berhikmat itu menjadi benih kelahiran kembali dan makanan bagi jiwa. Oleh karena itu, jangan sekali-kali tokoh-tokoh jemaat yang mengajar anggota-anggota jemaat lainnya, ataupun mereka yang diajar berani mencobai Allah dengan jalan menceraikan apa yang menurut perkenan-Nya dikehendaki-Nya supaya tetap tergabung erat. Begitu pula dahulu para Rasul, dan guru-guru yang telah menggantikan mereka, dengan penuh ketakwaan mengajar rakyat mengenai karunia Allah itu demi kemuliaan Allah dan untuk menekan seluruh keangkuhan manusia. Sementara itu, mereka rajin berupaya, melalui pengajaran kudus dari Injil, supaya rakyat itu tetap terkumpul di bawah pelayanan teratur Firman, sakramen-sakramen, dan disiplin gereja. Sebab, kasih karunia diberikan oleh pengajaran itu. Semakin Allah di dalam diri kita. Dengan demikian pekerjaan-Nya akan maju dengan cara yang paling tepat. Baik atas sarana-sarana itu, maupun atas buah dan keampuhannya yang mendatangkan keselamatan, hanya Allah saja yang patut menerima segala kemuliaan sampai selama-lamanya. Amin.

*Penolakan ajaran sesat*

Setelah menguraikan ajaran ortodoks maka sinode menolak ajaran-ajaran sesat orang yang mengajar sebagai berikut:

. Sebenarnya tidak dapat dikatakan, bahwa dosa turunan sendiri sudah cukup untuk membuat segenap umat manusia dihukum atau patut diganjar hukuman pada masa kini dan untuk selama-lamanya.
+
Mereka ini membantah perkataan Sang Rasul, 'Sama seperti dosa telah masuk ke dalam dunia oleh satu orang, dan oleh dosa itu juga maut, demikianlah maut itu telah menjalar kepada semua orang, karena semua orang telah berbuat dosa' (Rom 5:12). Dan, 'Penghakiman atas satu pelanggaran itu telah mengakibatkan penghukuman' (Rom 5:16). Dan 'Upah dosa ialah maut' (Rom 6:23).

. Pada mulanya, waktu manusia diciptakan, maka karunia-karunia rohani, sifat-sifat baik, dan kebajikan-kebajikan, seperti kebaikan, kesucian, dan kebenaran, tidak mungkin ada dalam kehendak manusia. Itulah sebabnya karunia-karunia itu tidak mungkin juga dipisahkan dari kehendak itu oleh kejatuhan dalam dosa.
+
Hal ini bertentangan dengan pemerian manusia sebagai gambar Allah seperti yang disajikan Sang Rasul dalam Efe 4:24. Di sana ia mengatakan, bahwa gambar Allah itu terdiri dari kebenaran dan kekudusan, yang keduanya tanpa ragu-ragu bertempat dalam kehendak.

. Dalam kematian rohani, karunia-karunia rohani yang dimiliki manusia tidak dipisahkan dari kehendak. Sebab, kehendak itu sendiri tidak pernah dirusak, tetapi hanya dirintangi oleh kegelapan akal-budi dan ketidaktetapan perasaan. Jika rintangan-rintangan ini dicabut, maka kehendak dapat memakai kekuatan yang bebas, yang telah ditanamkan ke dalamnya. Hal itu berarti, kehendak itu sanggup, dari dirinya sendiri, menghendaki dan memilih ataupun tidak menghendaki dan memilih hal apa pun yang baik yang dihadapkan kepadanya.
+
Ini ajaran baru dan sesat, yang cenderung memuji-muji kemampuan kehendak bebas. Hal ini bertentangan dengan perkataan Nabi Yeremia, 'Betapa liciknya hati, lebih licik daripada segala sesuatu, hatinya buruk' (Yer 17:9); dan dengan perkataan Sang Rasul, 'Sebenarnya dahulu kami semua juga terhitung di antara mereka, ketika kami hidup di dalam hawa nafsu daging dan menuruti kehendak daging dan pikiran kami yang jahat' (Efe 2:3).

. Manusia yang tidak dilahirkan kembali, sebenarnya tidak mati dalam dosa dalam arti yang sebenarnya dan secara menyeluruh. Pun ia tidak kehilangan sama sekali kekuatan untuk berbuat baik dalam arti rohani. Sebaliknya, ia masih dapat lapar dan haus akan kebenaran dan kehidupan serta mempersembahkan korban hati yang patah dan remuk, yang berkenan kepada Allah.
+
Hal-hal ini bertentangan dengan kesaksian-kesaksian Alkitab yang jelas, 'Kamu dahulu sudah mati karena pelanggaran-pelanggaran dan dosa-dosamu' (Efe 2:1-5). Dan, 'Segala kecenderungan hatinya selalu membuahkan kejahatan semata-mata' (Kej 6:5; 8:21). Lagi pula, hanya pada mereka yang dilahirkan kembali dan yang disebut berbahagialah terdapat lapar dan haus akan kelepasan dari sengsara dan akan kehidupan, dan hanya merekalah yang mempersembahkan korban hati yang patah kepada Allah (Mat 5:6 dan Maz 51:19).

. Anugerah umum (yang menurut mereka adalah terang kodrati) atau karunia-karunia yang masih tinggal sesudah kejatuhan manusia, dapat digunakan manusia yang sudah rusak dan yang kodrati itu dengan begitu tepat, sehingga oleh penggunaannya yang baik itu lama-kelamaan dan selangkah demi selangkah dapat diperolehnya karunia yang lebih besar, yaitu karunia Injili atau yang menyelamatkan, bahkan keselamatan itu sendiri. Dengan cara itu Allah dari pihak-Nya memperlihatkan kesediaan-Nya untuk menyatakan Kristus kepada semua orang, karena Dia memang menyajikan dengan secukupnya dan ampuh sarana-sarana yang dibutuhkan untuk penyataan Kristus dan untuk iman serta pertobatan.
+
Selain pengalaman segala zaman, Alkitab juga bersaksi bahwa ajaran ini tidak benar, 'Dia memberitakan firman-Nya kepada Yakub, ketetapan-ketetapan-Nya dan hukum-hukum-Nya kepada Israel. Dia tidak berbuat demikian kepada segala bangsa, dan hukum-hukum-Nya tidak mereka kenal' (Maz 147:19-20). 'Dalam zaman yang lampau Allah membiarkan semua bangsa menuruti jalannya masing-masing' (Kis 14:16). Dan, 'Roh Kudus mencegah mereka (Yaitu Paulus dan rekan-rekannya) untuk memberitakan Injil di Asia. Dan setibanya di Misia mereka mencoba masuk ke daerah Bitinia tetapi Roh Yesus tidak mengizinkan mereka' (Kis 16:6-7).

. Apabila manusia bertobat dengan sungguh-sungguh, Allah tidak mungkin mencurahkan sifat-sifat, kemampuan-kemampuan atau karunia-karunia yang baru ke dalam kehendaknya. Maka itu, iman - yang mengawali pertobatan kita dan yang menyebabkan kita disebut orang-orang beriman - bukanlah suatu sifat atau karunia yang dicurahkan Allah, melainkan perbuatan manusia semata-mata. Iman itu hanya dapat disebut 'karunia' dari sudut pandangan kemampuan untuk mencapainya.
+
Dengan hal ini, mereka membantah Kitab Suci, yang bersaksi bahwa Allah mencurahkan sifat-sifat baru dalam hati kita, yaitu iman, ketaatan, dan kesadaran akan kasih-Nya, 'Aku akan menaruh Taurat-Ku dalam batin mereka dan menuliskannya dalam hati mereka' (Yer 31:33). Dan, 'Aku akan mencurahkan air ke atas tanah yang haus, dan hujan lebat ke atas tempat yang kering. Aku akan mencurahkan Roh-Ku ke atas keturunanmu' (Yes 44:3). Dan, 'kasih Allah telah dicurahkan di dalam hati kita oleh Roh Kudus yang telah dikaruniakan kepada kita' (Rom 5:5). Begitu pula ajaran itu bertentangan dengan kebiasaan Gereja Allah yang tak berkeputusan, yang dalam Kitab Nabi Yeremia berdoa begini, 'bawalah aku kembali, supaya aku berbalik' (Yer 31:18).

. Kasih karunia yang olehnya kita berpaling kepada Allah itu tidak lain dari suatu anjuran lembut. Atau (sebagaimana diterangkan orang-orang lain), cara kerja yang paling mulia dalam hal pertobatan manusia serta yang paling cocok dengan kodratnya, ialah cara kerja melalui anjuran-anjuran. Tidak ada alasan untuk beranggapan seakan-akan kasih karunia yang menganjurkan ini sendiri saja tidak cukup untuk membuat manusia kodrati menjadi manusia rohani. Bahkan, Allah tidak menghasilkan persetujuan kehendak selain melalui cara menganjurkan itu. Keampuhan karya Allah, yang menyebabkan karya itu melebihi karya iblis, terdiri dari hal ini, bahwa Allah menjanjikan harta kekal, sedangkan iblis menjanjikan harta sementara.
+
Hal ini seluruhnya sama dengan ajaran Pelagius dan bertentangan dengan seantero Kitab Suci. Selain cara tadi, Kitab Suci mengenal cara berkarya Roh Kudus yang lain lagi dalam pertobatan manusia, yang jauh lebih ampuh dan ilahi, sebagaimana terdapat dalam Yehezkiel, 'Kamu akan Kuberikan hati yang baru, dan roh yang baru di dalam batinmu dan Aku akan menjauhkan dari tubuhmu hati yang keras dan Kuberikan kepadamu hati yang taat' (Yeh 36:26).

. Dalam hal kelahiran kembali manusia, Allah tidak memakai kekuatan-Nya yang mahakuasa, yang begitu rupa hingga olehnya kehendak manusia akan ditundukkan-Nya dengan cara yang unggul dan tak tergagalkan kepada iman dan pertobatan. Sebaliknya, meskipun semua karya kasih karunia sudah dilaksanakan, yang dipergunakan Allah untuk membuat manusia bertobat, namun manusia masih juga dapat melawan dan nyata-nyata melawan Allah dan Roh Kudus, yang berusaha demi kelahirannya kembali dan yang berkehendak melahirkannya kembali, sedemikian rupa hingga ia bahkan menghalangi sama sekali kelahirannya kembali. Maka itu, manusia sendiri berkuasa memutuskan apakah ia akan dilahirkan kembali atau tidak.
+
Hal ini tidak lain dan tidak bukan meniadakan sama sekali keampuhan kasih karunia Allah dalam pertobatan kita dan membuat kegiatan Allah yang mahakuasa kalah terhadap kehendak manusia. Hal ini bertentangan dengan apa yang diajarkan para rasul, 'Betapa hebat kuasa-Nya bagi kita yang percaya, sesuai dengan kekuatan kuasa-Nya' (Efe 1:19), dan, 'Supaya Allah dengan kekuatan-Nya menyempurnakan kehendakmu untuk berbuat baik dan menyempurnakan segala pekerjaan imanmu' (2Te 1:11), dan, 'Kuasa ilahi-Nya telah menganugerahkan kepada kita segala sesuatu yang berguna untuk hidup yang saleh' (2Pe 1:3).

. Rahmat dan kehendak bebas mengerjakan secara bersama, masing-masing untuk sebagian, awal pertobatan, dan rahmat tidak mendahului kegiatan kehendak bebas dalam hal urutan sebab-akibat. Artinya, setelah kehendak sendiri bergerak dan menuju ke pertobatan, barulah Allah membantu kehendak manusia dengan ampuh.
+
Gereja Lama pun sudah menolak ajaran ini pada zaman dahulu, ketika menolak kaum Pelagian, berdasarkan perkataan Sang Rasul, 'Jadi hal itu tidak tergantung pada kehendak orang atau usaha orang, tetapi kepada kemurahan hati Allah' (Rom 9:16). Demikian pula, 'Sebab siapakah yang menganggap engkau begitu penting? Dan apakah yang engkau punyai, yang tidak engkau terima?' (1Ko 4:7). 'Karena Allahlah yang mengerjakan di dalam kamu baik kemauan maupun pekerjaan menurut kerelaan-Nya' (Fil 2:13).

== V. Ketekunan orang kudus

. Mereka yang oleh Allah, menurut rencana-Nya, dipanggil ke persekutuan dengan Anak-Nya, Tuhan kita Yesus Kristus, dan yang dilahirkan-Nya kembali oleh Roh Kudus itu memang dilepaskan-Nya dari kekuasaan dan perhambaan dosa. Tetapi selama hidup ini Dia tidak melepaskan mereka sama sekali dari daging dan dari tubuh dosa.

. Dari situlah timbul dosa-dosa yang setiap hari dilakukan akibat kelemahan, dan noda yang masih melekat para perbuatan-perbuatan orang-orang kudus yang paling baik pun. Hal ini bagi mereka senantiasa menjadi alasan untuk merendahkan diri di hadapan Allah dan mencari perlindungan pada Kristus yang disalibkan itu. Oleh karena itu, mereka juga kian mematikan daging dengan berdoa dalam Roh dan dengan latihan-latihan suci dalam hidup saleh, dan mereka sangat rindu akan tujuan, yaitu kesempurnaan. Mereka berbuat demikian sampai saat mereka dilepaskan dari tubuh maut lalu bersama dengan Anak Domba Allah akan memerintah di surga.

. Lantaran sisa-sisa dosa yang masih tinggal di dalam mereka, dan juga oleh sebab godaan dunia dan iblis, maka orang-orang yang telah bertobat itu tidak sanggup bertekun dalam kasih karunia, seandainya mereka dibiarkan berusaha dengan kekuatan sendiri. Tetapi Allah adalah setia. Dengan penuh rahmat diteguhkan-Nya mereka dalam kasih karunia yang pernah diberikan kepada mereka, dan sampai akhirnya mereka dipelihara-Nya di dalamnya dengan kuat.

. Kuasa Allah yang olehnya orang yang benar-benar percaya diteguhkan-Nya dan dipelihara-Nya dalam kasih karunia itu adalah begitu besar, sehingga tidak mungkin dikalahkan oleh daging. Namun bimbingan dan dorongan Allah terhadap orang yang telah bertobat itu tidak selalu bersifat begitu rupa, sehingga tidak mungkin dalam perbuatan-perbuatan yang tertentu, karena kesalahan mereka sendiri, mereka menyimpang dari bimbingan kasih karunia dan menuruti godaan keinginan-keinginan daging. Oleh sebab itu mereka harus senantiasa berjaga-jaga dan berdoa supaya mereka jangan dibawa ke dalam pencobaan. Jika mereka tidak berbuat ini, maka mereka bisa saja diseret oleh daging, dunia, dan iblis sehingga melakukan dosa-dosa yang berat dan ngeri. Bahkan kadang-kadang mereka memang diseret secara nyata, dengan izin Allah yang adil. Hal itu diperlihatkan oleh peristiwa-peristiwa Daud, Petrus, dan orang-orang kudus yang lain, yang jatuh ke dalam dosa dengan begitu menyedihkan, sebagaimana digambarkan bagi kita dalam Alkitab.

. Dengan dosa yang sedemikian berat itu mereka sangat membangkitkan murka Allah; mereka melakukan kesalahan yang patut diganjar hukuman mati; mereka mendukakan Roh Kudus; untuk sementara waktu mereka menghentikan praktik kehidupan iman; mereka sangat melukai hati nurani dan kadang-kadang untuk sementara waktu mereka tidak merasakan lagi kasih karunia. Hal ini berlangsung sampai mereka membalik oleh penyesalan yang sungguh-sungguh, dan wajah kebapaan Allah kembali menyinari mereka.

. Sebab Allah, yang kaya akan rahmat, sesuai dengan rencana pemilihan yang tidak berubah-ubah, tidak menjauhkan sama sekali Roh Kudus dari orang-orang milik-Nya, bahkan tidak juga apabila mereka telah jatuh ke dalam dosa dengan cara yang menyedihkan. Dia juga tidak membiarkan mereka tersandung sedemikian, hingga mereka kehilangan karunia pengangkatan menjadi anak-anak Allah dan kedudukan sebagai orang yang dibenarkan, atau hingga mereka berbuat dosa yang mendatangkan maut, atau dosa yang menentang Roh Kudus, dan sama sekali ditinggalkan oleh Allah lalu menceburkan diri ke dalam kebinasaan yang kekal.

. Sebab, pertama-tama, tiap-tiap kali mereka jatuh ke dalam dosa dengan cara demikian, tetap dipelihara-Nya di dalam mereka benih-Nya yang tidak fana, yang olehnya mereka telah dilahirkan kembali, supaya benih itu tidak binasa atau terbuang. Selanjutnya sudah pasti mereka diperbarui-Nya dengan ampuh oleh Firman dan Roh-Nya, sehingga mereka bertobat. Maksudnya, supaya mereka sungguh-sungguh berdukacita menurut kehendak Allah karena dosa-dosa yang telah dilakukannya; oleh iman dan dengan hati yang patah dan remuk mereka memohon dan memperoleh pengampunan dalam darah Sang Pengantara; mereka merasakan kembali kasih karunia Allah, yang kini telah diperdamaikan dengan mereka; mereka menyembah kemurahan dan kesetiaan-Nya dan untuk selanjutnya mereka makin berusaha untuk mengerjakan keselamatan mereka dengan takut dan gentar.

. Maka, bukan karena jasa atau kekuatan mereka sendiri, melainkan karena belas kasihan Allah yang diberikan dengan cuma-cuma itu mereka beroleh hal ini, yaitu bahwa mereka tidak sama sekali kehilangan iman dan kasih karunia, atau untuk selama-lamanya tinggal dalam kejatuhan mereka dan akan binasa. Sejauh tergantung pada mereka, hal itu mudah saja terjadi, bahkan tanpa ragu-ragu akan terjadi. Tetapi dari sudut Allah hal itu mustahil, sebab keputusan-Nya tidak dapat diubah, janji-Nya tidak dapat diingkari, dan panggilan menurut rencana-Nya tidak dapat dicabut; begitu pula jasa, doa syafaat, dan pemeliharaan Kristus tidak mungkin ditiadakan dan juga pemeteraian dengan Roh Kudus tidak dapat digagalkan atau dimusnahkan.

. Orang percaya sendiri boleh yakin akan pemeliharaan orang-orang pilihan demi keselamatan mereka dan akan ketekunan iman orang yang sungguh-sungguh percaya. Mereka memang yakin akan hal itu, menurut ukuran iman yang membuat mereka percaya dengan teguh, bahwa mereka adalah anggota-anggota gereja yang sejati dan hidup, kini dan untuk selama-lamanya, dan bahwa mereka memiliki pengampunan dosa dan hidup yang kekal.

. Jadi, kepastian itu tidak timbul dari salah satu penyataan khusus, yang berlangsung tanpa atau di luar Firman, tetapi dari hal-hal berikut: Pertama, dari kepercayaan kepada janji-janji Allah yang telah dinyatakan-Nya dengan begitu berlimpah-limpah dalam Firman-Nya demi penghiburan kita. Kemudian, dari kesaksian Roh Kudus yang bersaksi bersama dengan roh kita bahwa kita adalah anak dan ahli waris Allah. Akhirnya, dari upaya yang sungguh-sungguh dan suci untuk memelihara hati nurani yang tetap murni dan untuk melakukan perbuatan-perbuatan baik. Andaikata orang-orang pilihan Allah dalam dunia ini harus kehilangan hiburan yang teguh ini, yaitu bahwa mereka akan memperoleh kemenangan, dan andaikata mereka harus kehilangan jaminan kemuliaan yang kekal yang tak berdusta itu, maka mereka adalah orang-orang yang paling malang dari semua manusia.

. Sementara itu, Alkitab bersaksi bahwa orang percaya selama hidup harus berjuang melawan bermacam-macam kebimbangan daging. Mereka dibuat menghadapi pencobaan yang berat sehingga tidak selalu merasakan keyakinan iman yang penuh dan kepastian tentang ketekunan ini. Tetapi Allah, sumber segala penghiburan, tidak akan membiarkan mereka dicobai melampaui kekuatan mereka, sebab di tengah pencobaan Dia memberikan juga jalan ke luar, dan oleh Roh Kudus Dia kembali merangsang di dalam mereka kepastian tentang ketekunan.

. Akan tetapi, kepastian tentang ketekunan ini sekali-kali tidak membawa orang yang benar-benar percaya itu pada kesombongan dan ketidakacuhan menurut daging. Sebaliknya, ketekunan itu sungguh-sungguh menjadi akar kerendahan hati, keseganan seorang anak, kesalehan yang sejati, kesabaran dalam segala perjuangan, doa-doa yang berapi, ketabahan dalam memikul salib dan dalam mengaku kebenaran, serta juga sukacita yang teguh di dalam Allah. Begitu pula perenungan anugerah itu justru merangsang mereka untuk dengan sungguh-sungguh dan tetap melakukan pengucapan syukur dan perbuatan baik. Hal ini nyata dari kesaksian-kesaksian Alkitab dan dari teladan orang kudus.

. Pada mereka yang dibangkitkan lagi sesudah jatuh ke dalam dosa, kepercayaan akan ketekunan itu tidak juga menghasilkan kecerobohan dan kealpaan dalam kesalehan, tetapi ikhtiar yang terlebih besar untuk mengikuti jalan-jalan Tuhan dengan saksama. Jalan-jalan itu telah dipersiapkan sebelumnya, supaya dengan menapakinya, mereka tetap memiliki kepastian tentang ketekunan mereka, dan supaya wajah Allah yang telah diperdamaikan dengan mereka tidak dipalingkan kembali dari mereka karena mereka telah menyalahgunakan kebaikan-Nya sebagai seorang Bapa, sehingga mereka jatuh ke dalam siksaan jiwa yang lebih berat lagi. Sebab bagi mereka yang takut akan Allah, memandang wajah-Nya itu lebih manis daripada hidup, tetapi apabila Allah menyembunyikan wajah-Nya maka bagi mereka hal itu lebih pahit daripada maut.

. Sebagaimana Allah telah berkenan memulai pekerjaan kasih karunia-Nya itu di dalam kita oleh pemberitaan Injil, begitu pula Dia memelihara, meneruskan, dan menyelesaikan pekerjaan itu. Caranya, dengan mendengarkan, membaca, dan merenungkan Injil, dan dengan nasihat-nasihat, ancaman-ancaman, janji-janji, serta juga dengan menggunakan sakramen-sakramen kudus.

. Ajaran tentang ketekunan orang yang sungguh-sungguh percaya dan kudus dan tentang kepastian tentang ketekunan itu, telah dinyatakan Allah dengan berlimpah-limpah dalam Firman-Nya demi kemuliaan nama-Nya dan demi penghiburan orang yang takut akan Dia, dan telah diterakan-Nya dalam hati orang percaya. Memang ajaran itu tidak dapat dipahami oleh daging, dibenci oleh iblis, diejek oleh dunia, disalahgunakan oleh mereka yang tidak memahaminya dan orang munafik, dan dibantah oleh para penyesat. Akan tetapi, mempelai perempuan Kristus senantiasa amat mengasihinya dan tetap membelanya sebagai suatu harta yang tak terkira nilainya. Allah akan menjaga, supaya ia akan berbuat seterusnya. Tidak ada rencana yang dapat dilaksanakan untuk melawan Dia dan tidak ada satu kuasa pun yang dapat bertahan terhadap Dia. Hanya Allah ini, yaitu Bapa, Anak, dan Roh Kudus, patut menerima hormat dan kemuliaan sampai selama-lamanya. Amin.

*Penolakan ajaran sesat*

Setelah menguraikan ajaran ortodoks maka sinode menolak ajaran-ajaran sesat orang yang mengajar sebagai berikut:

. Ketekunan orang-orang yang benar-benar percaya bukanlah hasil pemilihan atau pemberian Allah yang telah diperoleh melalui kematian Kristus, melainkan syarat perjanjian baru yang harus dipenuhi manusia melalui kehendaknya yang bebas, demi pemilihan dan pembenarannya yang menentukan (sebagaimana mereka menyebutnya).
+
Kitab Suci bersaksi, bahwa ketekunan merupakan akibat pemilihan dan diberikan kepada orang-orang pilihan oleh kekuatan kematian, kebangkitan, dan doa syafaat Kristus, 'Orang-orang yang terpilih telah memperolehnya. Dan orang-orang yang lain telah tegar hatinya' (Rom 11:7). Demikian pula, 'Dia, yang tidak menyayangkan Anak-Nya sendiri, tetapi menyerahkan-Nya bagi kita semua, bagaimanakah mungkin Dia tidak mengaruniakan segala sesuatu kepada kita bersama-sama dengan Dia? Siapakah yang akan menggugat orang-orang pilihan Allah? Allah, yang membenarkan mereka? Siapakah yang menghukum mereka? Kristus Yesus, yang telah mati? Bahkan lebih lagi: yang telah bangkit, yang juga duduk di sebelah kanan Allah, yang telah menjadi Pembela bagi kita? Siapakah yang akan memisahkan kita dari kasih Kristus?' (Rom 8:32-35).

. Allah memang mengaruniakan kepada orang percaya kekuatan-kekuatan yang cukup untuk bertekun, dan Dia bersedia memelihara kekuatan-kekuatan itu di dalamnya, jika orang ini menunaikan kewajibannya. Akan tetapi, setelah semua hal yang perlu untuk bertekun dalam iman dan yang kehendak Allah pakai untuk memelihara iman itu telah dipekerjakan, maka masih juga hal bertekun tidaknya manusia bergantung pada keputusan bebas kehendaknya.
+
Pandangan ini terang-terangan mengandung ajaran Pelagius. Maksudnya membebaskan manusia, namun pandangan ini menyebabkan manusia merampas kemuliaan Allah. Hal ini bertentangan dengan kesepakatan yang telah berlaku terus-menerus tentang ajaran Injil, yang membuat manusia kehilangan semua alasan untuk bermegah dan mengarahkan puji-pujian atas anugerah ini hanya kepada rahmat Allah semata-mata. Hal ini bertentangan juga dengan kesaksian Rasul, 'Dia juga akan meneguhkan kamu sampai kepada kesudahannya, sehingga kamu tak bercacat pada hari Tuhan kita Yesus Kristus' (1Ko 1:8).

. Orang yang sungguh-sungguh beriman dan dilahirkan kembali dapat saja kehilangan iman yang membenarkan serta kasih karunia dan keselamatan itu secara menyeluruh dan untuk selama-lamanya. Mereka bahkan acap kali nyata-nyata kehilangan hal-hal ini dan binasa untuk selama-lamanya.
+
Pendapat ini meniadakan karunia pembenaran dan kelahiran kembali serta perlindungan terus-menerus oleh Kristus. Hal ini bertentangan dengan perkataan tegas Rasul Paulus, bahwa "Kristus telah mati untuk kita, ketika kita masih berdosa. Lebih-lebih, karena kita sekarang telah dibenarkan oleh darah-Nya, kita pasti akan diselamatkan dari murka Allah" (Rom 5:8-9). Hal ini bertentangan juga dengan apa yang dikatakan oleh Rasul Yohanes, "Setiap orang yang lahir dari Allah, tidak berbuat dosa lagi; sebab benih ilahi tetap ada di dalam dia dan ia tidak dapat berbuat dosa, karena ia lahir dari Allah" (1Yo 3:9). Juga dengan perkataan Yesus Kristus, "Aku memberikan hidup yang kekal kepada domba-domba-Ku dan mereka pasti tidak akan binasa sampai selama-lamanya dan seorang pun tidak akan merebut mereka dari tangan-Ku. Bapa-Ku, yang memberikan mereka kepada-Ku, lebih besar daripada siapa pun, dan seorang pun tidak dapat merebut mereka dari tangan Bapa" (Yoh 10:28-29).

. Orang yang sungguh-sungguh percaya dan dilahirkan kembali dapat melakukan dosa yang mendatangkan maut, atau dosa yang menentang Roh Kudus.
+
Dalam pasal kelima surat kirimannya yang pertama, Rasul Yohanes berbicara mengenai orang yang melakukan dosa yang mendatangkan maut, dan melarang mendoakan mereka (1Yo 5:16-17), lalu dalam ayat 18 segera ditambahkannya, "Kita tahu, bahwa setiap orang yang lahir dari Allah, tidak berbuat dosa" (yaitu dosa yang demikian); "tetapi Dia yang lahir dari Allah melindunginya, dan di jahat tidak dapat menjamahnya" (1Yo 5:18).

. Dalam kehidupan ini, tak mungkin orang mendapat kepastian tentang ketekunannya di masa mendatang kalau tidak memperoleh penyataan khusus.
+
Ajaran ini mencabut hiburan teguh orang yang sungguh-sungguh percaya, yang mereka nikmati dalam hidup ini, dan kembali memasukkan kebimbangan orang Katolik Roma ke dalam Gereja. Di mana-mana Kitab Suci mengambil kepastian ini dari ciri-ciri khas anak-anak Allah, dan dari janji-janji Allah yang amat teguh, bukan dari suatu penyataan yang khusus dan luar biasa. Teristimewa Rasul Paulus, Makhluk apa pun tidak akan dapat memisahkan kita dari kasih Allah, yang ada dalam Kristus Yesus, Tuhan kita" (Rom 8:39). Dan Yohanes berkata, "Barangsiapa menuruti segala perintah-Nya, ia diam di dalam Allah dan Allah di dalam dia. Dan demikianlah kita ketahui, bahwa Allah ada di dalam kita, yaitu Roh yang telah Dia karuniakan kepada kita" (1Yo 3:24).

. Ajaran tentang kepastian tentang ketekunan dan keselamatan itu pada hakikatnya bersifat "bantal bagi daging" dan merupakan bahaya bagi kesalehan, kesusilaan, doa-doa, dan semua hal lainnya, yang termasuk praktik hidup yang saleh. Sebaliknya, meragukan ajaran itu merupakan perbuatan yang terpuji.
+
Mereka ini memperlihatkan, bahwa mereka tidak mengenal keampuhan kasih karunia ilahi dan karya Roh Kudus yang berdiam di dalam manusia. Mereka juga membantah Rasul Yohanes yang dengan tegas mengajar yang sebaliknya, "Saudara-saudaraku yang kekasih, sekarang kita adalah anak-anak Allah, tetapi belum nyata apa keadaan kita kelak; akan tetapi kita tahu, bahwa apabila Kristus menyatakan diri-Nya, kita akan menjadi sama seperti Dia, sebab kita akan melihat Dia dalam keadaan-Nya yang sebenarnya. Setiap orang yang menaruh pengharapan itu kepada-Nya, menyucikan diri sama seperti Dia yang adalah suci" (1Yo 3:2-3). Lagi pula ajaran ini dibantah oleh teladan orang-orang kudus dalam Perjanjian Lama dan Perjanjian Baru. Mereka merasa yakin akan ketekunan dan keselamatan mereka, namun tetap bertekun dalam doa dan dalam semua hal lainnya, yang termasuk praktik hidup yang saleh.

. Iman orang-orang yang percaya untuk sementara waktu saja, tidak berbeda dari iman yang membenarkan dan yang menyelamatkan, kecuali dalam hal panjang waktunya.
+
Kristus sendiri dengan jelas menunjukkan tiga macam perbedaan lagi antara mereka yang hanya percaya untuk sementara waktu dan orang-orang yang benar-benar percaya. Dalam Mat 13:20 dyb. dan Luk 8:13 dyb. dikatakanNya, bahwa orang-orang yang percaya untuk sementara waktu menerima benih di tanah yang berbatu-batu; mereka tidak berakar dan tidak berbuah. SebaliknYa, orang-orang yang benar-benar percaya menerima benih di tanah yang baik atau di dalam hati yang baik; mereka berakar kuat dan dengan tiada henti-hentinya serta tekun menghasilkan buah, meskipun tidak sama jumlahnya.

. Apabila manusia telah kehilangan kelahiran kembali yang pertama, maka tidak mustahil ia dilahirkan kembali sekali lagi, bahkan beberapa kati.
+
Melalui ajaran ini, mereka menyangkal ketidakfanaan benih Allah, yang olehnya kita dilahirkan kembali. Hal ini bertentangan dengan kesaksian Rasul Petrus, "Kamu telah dilahirkan kembali bukan dari benih yang fana, tetapi dari benih yang tidak fana" (1Pe 1:23).

. Kristus tidak pernah berdoa, agar supaya orang-orang beriman akan bertekun dalam iman dengan tak tergagalkan.
+
Mereka membantah perkataan Kristus sendiri, "Aku telah berdoa untuk engkau, supaya imanmu jangan gugur" (Luk 22:32). Mereka juga membantah kesaksian pengarang Injil Yohanes, yaitu bahwa Kristus telah berdoa bukan hanya untuk rasul-rasul, tetapi juga untuk semua orang yang akan menjadi percaya melalui pemberitaan para rasul itu, "Ya Bapa yang kudus, Peliharalah mereka dalam nama-Mu; Aku tidak meminta, supaya Engkau mengambil mereka dari dunia, tetapi supaya Engkau melindungi mereka dari yang jahat (Yoh 17:11,15,20)."

== Kata Penutup

Inilah uraian yang jelas, sederhana, dan jujur tentang ajaran ortodoks sehubungan dengan Kelima Pasal yang sedang dipersoalkan di Negeri Belanda, beserta penolakan ajaran-ajaran sesat yang telah menyebabkan Gereja-gereja Belanda dikacaukan selama beberapa waktu. Sinode berpendapat, uraian dan penolakan ini diambil dari Firman AllaH dan sesuai dengan pengakuan iman Gereja-gereja Reformasi. Dari sini nyatalah dengan jelas, bahwa, bertentangan dengan segala kebenaran, keadilan, dan kasih, orang-orang Yang justru sama sekali tidakpatut berbuat demikian telah berikhtiar membohongi rakyat dengan menyatakan:

Ajaran Gereja-gereja Reformasi mengenai Predestinasi dan mengenai pokok pokok yang berhubungan dengannya, karena sifatnya sendiri dan disebabkan dinamikanya sendiri, sama sekali mengasingkan hati manusia dari kesalehan dan peribadatan. Ajaran ini merupakan 'bantal bagi daging dan iblis' serta perbentengan iblis, dan menjadi titik tolaknya dalam menghadang semua orang, melukai kebanyakan orang, dan mematikan banyak orang dengan panah-panah keputusasaan atau ketidakacuhan.

Ajaran ini menjadikan Allah Pembuat dosa, Allah yang tidak adil, lalim, dan munafik. Ajaran ini tidak lain dan tidak bukan pembaruan ajaran Stoa,(1) Mani,(2) kaum Libertin,(3) dan Islam.

Ajaran ini membawa orang-orang kepada ketidakacuhan yang jasmani, karena mereka akan membohongi diri mereka, seakan-akan cara hidup orang pilihan sama sekali tidak menentukan keselamatan mereka, sehingga mereka dengan tenang saja boleh melakukan segala macam kejahatan yang ngeri.

Adapun mereka yang telah ditolak, sekalipun mereka sungguh-sungguh melaksanakan segala perbuatan orang-orang kudus, hal itu tidak mungkinbermanfaat bagi keselamatan mereka.

Dengan ajaran ini dikatakan bahwa Allah, hanya karena tindakan sewenang-wenang kehendak-Nya saja, tanpa memperhatikan atau mempedulikan dosa apa pun, telah menentukan dan menciptakan bagian terbesar dunia ini, bagi kebinasaan yang kekal.

Penolakan adalah penyebab ketidakpercayaan dan kefasikan, sama seperti pemilihan adalah sumber dan penyebab iman serta perbuatan yang baik.

Allah merenggut banyak anak orang percaya yang tak bersalah dari susu ibunya dan dengan lalim membuang mereka ke dalam api neraka, sehingga baik darah Kristus, maupun pembaptisan atau doa Gereja waktu mereka dibaptis tidak mungkin bermanfaat bagi mereka.

Dan banyak tuduhan sejenis, yang tidak termasuk pengakuan iman Gereja-gereja Reformasi, bahkan sama sekali ditolak Gereja-gereja itu dengan rasa jijik.

Itulah sebabnya Sinode Dordrecht ini meminta dengan mendesak, demi nama Tuhan, kepada semua orang yang dengan saleh memanggil nama Juruselamat kita Yesus Kristus, agar supaya mereka jangan menilai iman Gereja-gereja Reformasi atas dasar fitnah yang dikumpulkan dari sana sini, jangan juga atas dasar perkataan pribadi beberapa guru lama atau baru, yang sering dikutip dengan itikad jahat, diputarbalikkan, dan diterangkan dengan salah. Hendaklah mereka menilai iman Gereja-gereja Reformasi berdasarkan karangan-karangan pengakuan iman yang umum dari Gereja-gereja itu sendiri dan berdasarkan uraian ini mengenai ajaran yang benar, yang telah ditetapkan dengan persetujuan tiap-tiap anggota seluruh Sinode.

Selanjutnya Sinode dengan sungguh-sungguh menegur para pemfitnah agar mempertimbangkan betapa beratnya hukuman Allah yang mereka datangkan atas diri mereka sendiri, mereka yang mengucapkan kesaksian dusta terhadap sedemikian banyak gereja dan terhadap karangan-karangan pengakuan iman sedemikian banyak gereja, yang menggelisahkan hati nurani orang-orang yang imannya lemah dan yang berupaya untuk membuat banyak orang merasa curiga terhadap persekutuan orang yang benar-benar percaya.

Akhirnya Sinode ini mendorong semua rekan Pelayan dalam Injil Kristus, supaya mereka bertindak saleh dan alim bilamana mengupas ajaran ini di sekolah-sekolah dan di gereja-gereja. Hendaklah mereka mengarahkannya, baik secara lisan maupun secara tertulis, kepada kemuliaan Nama Allah, kesucian hidup, dan penghiburan hati yang hancur. Hendaklah juga dalam pikiran dan bicara mereka berpegang pada Alkitab, sesuai dengan kesepakatan bersama tentang iman. Akhirnya, hendaklah mereka menahan diri dari setiap cara bicara yang melewati batas-batas yang telah ditetapkan bagi kita dalam hal menentukan arti sebenarnya Kitab-kitab Suci, dan yang dapat menyediakan alasan yang wajar bagi orang yang suka menggunakan penalaran yang muluk-muluk tetapi menyesatkan, untuk menista atau memfitnah ajaran Gereja-gereja Reformasi.

Kami berdoa supaya Anak Allah, Yesus Kristus, yang sedang duduk di sebelah kanan Bapa-Nya dan yang memberi karunia-karunia kepada manusia, menguduskan kita dalam kebenaran, membawa mereka yang telah sesat itu kembali kepada kebenaran, menutupi mulut orang yang memfitnah ajaran sehat, dan mengaruniakan Roh hikmat dan pengertian kepada pelayan-pelayan Firman-Nya yang setia, agar semua perkataan mereka berguna bagi kemuliaan Allah dan bagi pembinaan para pendengarnya. Amin.