:page-title     : ToC - intro
:page-signed-by : Deo Valiandro. M <valiandrod@gmail.com>
:page-layout    : default
:page-category  : Teori Komputasi
:page-time      : 2021-12-03T07:12:45
:page-update    : 2022-05-10T13:38:00
:page-math: true


== Latar belakang

Sebenarnya, dari tahun 2019 saya sudah ingin mempelajari tentang teori
komputasi. Hal ini bermula saat teman-teman Ilkom'16 mengambil matkul tekom,
namun saya sendiri tidak sempat mengambil matkul tersebut akibat banyaknya
matkul yang saya ambil pada semester itu.

Sehingga saya memutuskan untuk belajar tekom secara mandiri melalui buku dan
youtube. Buku yang saya baca adalah:

. *Formal Language - A Practical Introduction* oleh Adam Brooks Webber
. *Introduction to the theory of computation* oleh Michael Sipser

dan dari beberapa channel youtube seperti Neso Academy.


== Materi

. Alfabet adalah finite set simbol, contohnya $\Sigma = {a, b}$ adalah set
simbol dari $a$ dan $b$,

. String adalah urutan rangkaian simbol (kosong sampai infinity simbol),
contohnya $aaaa$ dan $10001$. Dengan $|ab| = 2$, $|\epsilon| = 0$, 'zero' ("the
string of no symbols") ${} \neq {\epsilon}$.

$$\begin{aligned}
x^n &= xx \cdots x, \text{n times} \\
x^0 &= \epsilon \\
x^1 &= x \\
x^2 &= xx
\end{aligned}$

. Languages adalah set string atas fixed alfabet, dengan $\Sigma^{\ast}$
adalah set semua string atas $\Sigma$ (_Kleene closure_), contohnya
${a^{\ast}} = {\epsilon, a, aa, aaa, \cdots}$. Dengan menggunakan $x \in
\Sigma^{\ast}$ adalah $x$ atas alfabet $\Sigma$.

Kecuali $\Sigma = \{\}$, Kleene closure atas alfabet adalah infinity set.

_The Pragmatic Programmer_ <<pp>> should be required reading for all developers.
To learn all about design patterns, refer to the book by the "`Gang of Four`" <<gof>>.

[bibliography]
== References

* [[[pp]]] Andy Hunt & Dave Thomas. The Pragmatic Programmer:
From Journeyman to Master. Addison-Wesley. 1999.
* [[[gof,gang]]] Erich Gamma, Richard Helm, Ralph Johnson & John Vlissides.
Design Patterns: Elements of Reusable Object-Oriented Software. Addison-Wesley. 1994.