---
title       : CSS
signed-by   : Deo Valiandro. M <valiandrod@gmail.com>
layout      : default
time        : 2016-09-01
---


Bermula dari pelajaran CSS yang didapatkan di mata kuliah Pengantar Pemrograman,
maka sebagai bahan pelajaran, kami mencoba membuat css sangat sederhana.
Rancangan CSS ini akan diperbaharui kedepannya.

== Font

Saya pribadi pikir kita tidak perlu memuat terlalu banyak font, memberatkan
website saja. Yang pasti tulisan bisa dibaca dengan jelas.

Saya akhirnya menggunakan font [.link]#https://rsms.me/inter/[Inter]#
footnote:[Inter a trademark of Rasmus Andersson. Font vendor ID: RSMS] untuk paragraf,
[.google]#https://fonts.google.com/specimen/DM+Serif+Display[DM Serif Display]# 
untuk header dan
[.google]#https://fonts.google.com/specimen/DM+Mono[DM Mono]# untuk monospace.

=== Update

Saya kemudian mengganti dengan menggunakan beberapa font baru,

1. [.google]#https://fonts.google.com/specimen/Source+Serif+4[Source Serif]#
2. Deutsche Zierschrift

== Width

Saya selalu mengikuti [.wikipedia]#https://en.wikipedia.org/wiki/Characters_per_line[CPL]#
yaitu 80 karakter per baris.

== Highlight

Untuk urusan highlight code, saya serahkan ke
[.github]#https://github.com/rouge-ruby/rouge[rouge]#. Saya menggunakan
##gruvbox.light## dengan beberapa customisasi.

Contohnya saja:

[source, go]
----
package main

import "fmt"

type PrintString func(string2 string) string

func sayBellow(name string, printString PrintString) string {
    bellow := printString(name)
    firstString := ":D " + bellow
    return firstString
}

func printString(wow string) string {
    return wow
}

func main() {
    fmt.Println(sayBellow("satu", printString))
}
----

== Lain-lain

=== Key

kbd:[Ctrl + s]

=== Marked

##Hello my friend##

=== Inline Code

`run()`

=== Blockquote

> "Bad programmers worry about the code. Good programmers worry about data
> structures and their relationships." 
> -- Linus Torvalds
