:page-title     : CSS
:page-signed-by : Deo Valiandro. M <valiandrod@gmail.com>
:page-layout    : default
:page-time      : 2016-09-01


Bermula dari pelajaran CSS yang didapatkan di mata kuliah Pengantar Pemrograman,
maka sebagai bahan pelajaran, kami mencoba membuat css sangat sederhana.
Rancangan CSS ini akan diperbaharui kedepannya.

== Font

Saya pribadi pikir kita tidak perlu memuat terlalu banyak font, memberatkan
website saja. Yang pasti tulisan bisa dibaca dengan jelas.

Saya akhirnya menggunakan font https://rsms.me/inter/[Inter] untuk paragraf,
https://fonts.google.com/specimen/DM+Serif+Display[DM Serif Display] untuk
header dan https://fonts.google.com/specimen/DM+Mono[DM Mono] untuk monospace.

== Width

Saya selalu mengikuti https://en.wikipedia.org/wiki/Characters_per_line[CPL]
yaitu 80 karakter per baris.

== Highlight

Untuk urusan highlight code, saya serahkan ke
https://github.com/rouge-ruby/rouge[rouge]. Saya menggunakan gruvbox.light
dengan beberapa customisasi.

== Lain-lain

=== Key

kbd:[Ctrl + s]

=== Marked

##Hello my friend##

=== Inline Code

`run()`

=== Blockquote

> "Bad programmers worry about the code. Good programmers worry about data
> structures and their relationships." 
> -- Linus Torvalds
