= Katekismus Heidelberg

Sumber dari Sabda https://reformed.sabda.org/node/128

. _Pert. Apakah satu-satunya penghiburan Saudara, baik pada masa hidup maupun pada waktu mati?_
+
Jaw. Bahwa aku, dengan tubuh dan jiwaku, baik pada masa hidup maupun pada waktu mati (a), bukan milikku (b), melainkan milik Yesus Kristus, Juruselamatku yang setia (c). Dengan darah-Nya yang tak ternilai harganya Dia telah melunasi seluruh utang dosaku (d) dan melepaskan aku dari segala kuasa iblis (e). Dia juga memelihara aku (f), sehingga tidak sehelai rambut pun jatuh dari kepalaku di luar kehendak Bapa yang ada di sorga (g), bahkan segala sesuatu harus berguna untuk keselamatanku (h). Karena itu juga, oleh Roh-Nya yang Kudus, Dia memberiku kepastian mengenai hidup yang kekal (i), dan menjadikan aku sungguh-sungguh rela dan siap untuk selanjutnya mengabdi kepada-Nya (j).

. _Pert. Berapa pokok yang perlu Saudara ketahui, supaya dengan penghiburan ini Saudara hidup dan mati dengan bahagia?_
+
Jaw. Tiga pokok (a). Pertama. betapa besarnya dosa dan sengsaraku (b). Kedua, bagaimana aku mendapat kelepasan dari semua dosa dan sengsaraku (c). Ketiga, bagaimana aku harus bersyukur kepada Allah atas kelepasan yang demikian itu (d).

. _Pert. Dari mana Saudara mengetahui sengsara Saudara?_
+
Jaw. Dari hukum Taurat Allah (a).

. _Pert. Apa yang dituntut hukum Taurat Allah dari kita?_
+
Jaw. Itu diajarkan Kristus kepada kita secara ringkas dalam Mat 22:37-40, 'Kasihilah Tuhan, Allahmu, dengan segenap hatimu, dengan segenap jiwamu, dengan segenap akal-budimu, dan dengan segenap kekuatanmu. Itulah hukum yang terutama dan yang pertama. Dan hukum yang kedua, yang sama dengan itu, ialah: Kasihilah sesamamu manusia seperti dirimu sendiri. Pada kedua hukum inilah tergantung seluruh hukum Taurat dan kitab para nabi.'

. _Pert. Dapatkah Saudara melaksanakan semua ini dengan sempurna?_
+
Jaw. Tidak (a), karena menurut kodratku aku cenderung membenci Allah dan sesamaku manusia (b).

. _Pert. Jadi, apakah Allah telah menjadikan manusia begitu jahat dan buruk?_
+
Jaw. Sekali-kali tidak (a). Tetapi Allah telah menjadikan manusia baik dan menurut gambar-Nya (b), artinya, dengan kebenaran dan kesucian yang sejati, supaya manusia dapat mengenal Allah Penciptanya secara benar, mengasihi-Nya dengan sebulat hati, dan hidup bersama Dia dalam kebahagiaan yang kekal untuk memuji dan memuliakan Dia (c).

. _Pert. Jadi, dari mana asal watak manusia yang seburuk itu?_
+
Jaw. Dari kejatuhan ke dalam dosa dan ketidaktaatan nenek moyang kita, Adam dan Hawa, di taman Firdaus (a). Di situ tabiat kita menjadi sedemikian buruk, sehingga kita semua dikandung dan dilahirkan dalam dosa (b).

. _Pert. Tetapi, begitu rusakkah kita, sehingga kita sama sekali tidak sanggup berbuat apa pun yang baik, dan hanya cenderung pada yang jahat saja?_
+
Jaw. Ya (a), kecuali jika kita dilahirkan kembali oleh Roh Allah (b).

. _Pert. Apakah Allah memperlakukan manusia dengan tidak adil bila menuntut dalam hukum-Nya sesuatu yang tidak dapat dilaksanakan oleh manusia?_
+
Jaw. Tidak (a), karena Allah telah menjadikan manusia sedemikian rupa, hingga ia dapat melaksanakannya (b). Tetapi oleh bisikan iblis (c) dan oleh ketidaktaatannya yang disengaja, manusia telah bertindak sedemikian, sehingga ia bersama keturunannya kehilangan karunia-karunia itu.

. _Pert. Apakah Allah hendak membiarkan ketidaktaatan dan kemurtadan semacam itu tanpa hukuman?_
+
Jaw. Tidak. Sebaliknya, Dia sangat murka (a), baik atas dosa turunan maupun atas dosa yang kita perbuat sendiri. Dia hendak menghukumnya dengan hukuman yang adil, baik di dunia ini maupun di akhirat (b), sebagaimana Dia telah berfirman, 'Terkutuklah orang yang tidak setia melakukan segala sesuatu yang tertulis dalam kitab hukum Taurat' (Gal 3:10).

. _Pert. Bukankah Allah juga penyayang?_
+
Jaw. Sungguh Allah itu penyayang (a), tetapi Dia juga adil (b). Oleh sebab itu, keadilan-Nya menuntut supaya dosa yang diperbuat terhadap Kemuliaan Allah yang Tertinggi itu dihukum dengan hukuman yang tertinggi juga, yaitu hukuman yang kekal atas tubuh dan jiwa.

. _Pert. Menurut hukuman Allah yang adil itu kita patut mendapat hukuman di dunia ini dan di akhirat. Maka adakah cara kita dapat luput dari hukuman itu dan beroleh kembali anugerah Allah?_
+
Jaw. Allah menghendaki, supaya tuntutan-tuntutan keadilan-Nya dipenuhi (a). Oleh sebab itu, kita wajib melaksanakan pelunasan sepenuhnya, apakah dengan berupaya sendiri atau oleh upaya pihak lain (b).

. _Pert. Dapatkah kita melaksanakan pelunasan dengan berupaya sendiri?_
+
Jaw. Sama sekali tidak. Bahkan, tiap-tiap hari kita menambah hutang kita (a).

. _Pert. Mungkinkah ditemukan suatu makhluk semata, yang dapat melaksanakan pelunasan bagi kita?_
+
Jaw. Tidak mungkin. Pertama, Allah tidak mau menjatuhkan hukuman terhadap makhluk lain karena kesalahan yang diperbuat manusia (a). Kedua, tidak ada makhluk semata yang sanggup menanggung beban murka Allah yang kekal atas dosa dan membebaskan makhluk-makhluk lain darinya (b).

. _Pert. Jadi, Pengantara dan Penebus yang bagaimana yang perlu kita cari?_
+
Jaw. Seorang Pengantara dan Penebus yang adalah manusia sejati (a) dan benar (b), tetapi yang kekuatan-Nya melebihi segala makhluk, artinya yang juga Allah yang sejati (c).

. _Pert. Mengapa Dia harus seorang manusia sejati dan benar?_
+
Jaw. Sebab keadilan Allah menuntut, supaya pembayaran untuk dosa dilakukan oleh kodrat manusia yang telah berdosa itu (a), sedangkan seorang manusia tidak sanggup melakukan pembayaran untuk dosa orang lain karena dia sendiri pun seorang berdosa (b).

. _Pert. Mengapa Dia harus juga Allah sejati?_
+
Jaw. Supaya dengan kuasa keallahan-Nya (a) Dia dapat menanggung (b) beban murka Allah atas kemanusiaan-Nya (c), memperoleh kebenaran dan kehidupan bagi kita, dan mengembalikannya kepada kita (d).

. _Pert. Tetapi, siapakah Pengantara itu, yang adalah Allah yang sejati (a), dan juga manusia yang sejati (b) dan benar (c)?_
+
Jaw. Tuhan kita Yesus Kristus (d), yang telah dikaruniakan oleh Allah kepada kita untuk menjadi hikmat, kebenaran, pengudusan, dan penebusan yang sempurna bagi kita (e).

. _Pert. Dari mana Saudara mengetahui hal itu?_
+
Jaw. Dari Injil yang kudus. Mula-mula, Allah sendiri telah menyatakannya di Taman Firdaus (a). Kemudian Dia menyuruh para bapak leluhur (b) dan para nabi (c) yang kudus mengabarkannya, dan memperlihatkan bayangannya melalui kurban- kurban dan upacara-upacara lain menurut hukum Taurat Allah (d). Akhirnya Dia menggenapinya melalui Anak-Nya yang tunggal (e).

. _Pert. Apakah semua orang diselamatkan oleh Kristus, sama seperti mereka telah terkutuk oleh karena Adam?_
+
Jaw. Tidak semua orang (a), tetapi hanya mereka yang oleh iman yang sejati dijadikan anggota tubuh-Nya dan menerima seluruh karunia-Nya (b).

. _Pert. Apa iman yang sejati itu?_
+
Jaw. Iman yang sejati adalah keyakinan atau pengetahuan yang pasti yang membuat aku mengakui sebagai kebenaran segala sesuatu yang dinyatakan Allah kepada kita di dalam Firman-Nya, dan juga kepercayaan yang teguh (b), yang dikerjakan dalam hatiku oleh Roh Kudus (c), melalui Injil (d). Isinya ialah bahwa pengampunan dosa dan kebenaran serta keselamatan yang kekal (e) telah dikaruniakan tidak hanya kepada orang lain saja, tetapi juga kepadaku sendiri, oleh rahmat Tuhan semata-mata, hanya berdasarkan jasa-jasa Kristus saja (f).

. _Pert. Apa yang perlu diimani oleh seorang Kristen?_
+
Jaw. Segala sesuatu yang dijanjikan kepada kita dalam Injil (a). Isi pokoknya diajarkan kepada kita melalui Pasal-pasal Pengakuan Iman Kristen yang am dan pasti.

. _Pert. Bagaimana bunyi Pasal-pasal Pengakuan Iman itu?_
+
Jaw. Aku percaya kepada Allah Bapa, Yang mahakuasa, Khalik langit dan bumi.
Dan kepada Yesus Kristus, Anak-Nya yang tunggal, Tuhan kita,
yang dikandung dari Roh Kudus,
lahir dari anak dara Maria,
yang menderita di bawah pemerintahan Pontius Pilatus,
disalibkan, mati dan dikuburkan,
turun ke dalam kerajaan maut,
pada hari yang ketiga bangkit pula dari antara orang mati,
naik ke sorga, duduk di sebelah kanan Allah, Bapa yang Mahakuasa,
dan akan datang dari sana untuk menghakimi orang yang hidup dan yang mati.
Aku percaya kepada Roh Kudus.
Aku percaya adanya gereja (Kristen) yang kudus dan am,
persekutuan orang kudus,
pengampunan dosa,
kebangkitan daging,
dan hidup yang kekal.

. _Pert. Pengakuan Iman itu dibagi atas berapa bagian?_
+
Jaw. Tiga bagian. Yang pertama mengenai Allah Bapa dan penciptaan kita. Yang kedua mengenai Allah Anak dan penebusan kita. Yang ketiga mengenai Allah Roh Kudus dan pengudusan kita.

. _Pert. Mengingat bahwa hanya ada satu Zat ilahi saja (a), apa sebabnya Saudara menyebutkan Bapa, Anak, dan Roh Kudus?_
+
Jaw. Karena demikianlah Allah menyatakan diri-Nya dalam Firman-Nya (b). Ketiga Pribadi yang berbeda-beda itu merupakan Allah yang esa, yang sejati dan kekal (c).

. _Pert. Apa yang Saudara percayai bila Saudara berkata, Aku percaya kepada Allah Bapa, Yang mahakuasa, Khalik langit dan bumi?_
+
Jaw. Bahwa Bapa yang kekal dari Tuhan kita Yesus Kristus, yang telah menciptakan langit dan bumi serta segala isinya dari yang tiada (a), dan juga tetap memelihara dan memerintahnya menurut rencana-Nya yang kekal dan pemeliharaan-Nya (b), adalah Allah dan Bapaku karena Anak-Nya, yaitu Kristus (c). Aku percaya kepada-Nya, bahkan aku tidak meragukan, Dia akan memeliharaku dalam semua kebutuhan tubuh dan jiwaku (d), dan juga mengubah segala bencana yang ditimpakan-Nya atasku di dunia yang penuh sengsara ini, menjadi kebaikan untukku (e). Sebagai Allah yang Mahakuasa Dia memang sanggup berbuat demikian (f), dan sebagai Bapa yang setiawan Dia berkehendak pula melakukannya (g).

. _Pert. Apa itu 'pemeliharaan Allah' menurut Saudara?_
+
Jaw. Kekuatan Allah, yang mahakuasa dan yang hadir di segala tempat (a). Dengannya Dia memelihara langit dan bumi serta semua makhluk seakan-akan dengan tangan-Nya sendiri, dan memerintahnya (b), sehingga daun dan rumput, hujan dan kemarau (c), masa kelimpahan dan kekurangan, makanan dan minuman, sehat dan sakit (d), kekayaan dan kemiskinan (e), dan segala hal tidak menimpa kita secara kebetulan, tetapi datang dari tangan Bapa saja (f).

. _Pert. Apa manfaatnya bagi kita kalau kita mengetahui bahwa Allah telah menciptakan segala sesuatu dan tetap merawatnya melalui pemeliharaan-Nya?_
+
Jaw. Berkat pengetahuan itu, kita dapat bersabar di tengah segala kesusahan (a) dan bersyukur dalam kelimpahan (b). Untuk masa depan juga kita menaruh kepercayaan penuh kepada Allah dan Bapa kita yang setia itu (c), bahwa tidak satu makhluk pun akan dapat menceraikan kita dari kasih-Nya (d). Sebab semuamakhluk berada di tangan-Nya, sehingga mereka tidak dapat bergerak setapak pun melawan kehendak-Nya (e).

. _Pert. Mengapa Anak Allah dinamakan Yesus, yang artinya 'Juruselamat'?_
+
Jaw. Sebab Dia menyelamatkan kita dari semua dosa kita (a). Lagi pula, sebab kita tidak boleh mencari dan tidak mungkin mendapatkan keselamatan dalam bentuk apa pun pada orang lain (b).

. _Pert. Apakah orang-orang yang mencari keselamatan dan kebahagiaan pada orang-orang kudus atau pada dirinya sendiri, atau pada apa pun yang lain, percaya juga kepada Yesus, Juruselamat satu-satunya?_
+
Jaw. Tidak. Sebaliknya, mereka nyata-nyata menyangkal Yesus, Juruselamat satu-satunya, meskipun dengan mulut mereka bermegah di dalam Dia (a). Karena di antara dua ini hanya satu yang benar: Yesus itu bukan Juruselamat yang sempurna, atau mereka yang menerima Juruselamat ini dengan iman yang benar tidak dapat tidak akan memperoleh dalam Dia segala sesuatu yang diperlukan untuk keselamatannya (b).

. _Pert. Mengapa Dia dinamakan Kristus, yang artinya 'Yang diurapi'?_
+
Jaw. Sebab Dia telah ditetapkan oleh Allah Bapa dan diurapi dengan Roh Kudus (a), menjadi Nabi dan Guru, Imam Besar, dan Raja kita. Sebagai Nabi dan Guru kita yang tertinggi (b), Dia telah menyatakan kepada kita dengan sempurna seluruh rencana dan kehendak Allah yang tersembunyi mengenai penebusan kita (c). Sebagai Imam Besar kita satu-satunya (d), Dia telah menebus kita dengan kurban satu-satunya, yaitu tubuh-Nya sendiri (e), dan senantiasa menjadi Pengantara kita di hadapan Allah dengan doa syafaat-Nya (f). Sebagai Raja kita yang kekal, Dia memerintah kita dengan Firman dan Roh-Nya serta melindungi dan memelihara kita sehingga tetap memiliki keselamatan yang telah diperoleh-Nya (g).

. _Pert. Tetapi, mengapa Saudara disebut orang Kristen? (a)_
+
Jaw. Sebab aku, melalui iman, adalah anggota tubuh Kristus (b), dan dengan demikian mendapat bagian dalam pengurapan-Nya (c). Tujuannya supaya aku mengakui nama-Nya (d), mempersembahkan diriku kepada-Nya menjadi korban syukur yang hidup (e), di dalam hidup ini berperang melawan dosa dan iblis dengan hati nurani yang bebas dan tulus (f), dan kelak di akhirat bersama-sama Dia memerintah segala makhluk untuk selama-lamanya (g).

. _Pert. Mengapa Dia dinamakan Anak Allah yang tunggal, padahal kita pun menjadi anak-anak Allah?_
+
Jaw. Sebab hanya Kristus saja yang adalah Anak Allah yang sehakikat dan yang sama-sama kekal (a). Sebaliknya, kita diangkat menjadi anak-anak Allah karena Dia, berdasarkan kasih karunia (b).

. _Pert. Mengapa Saudara menyebut Dia Tuhan kita?_
+
Jaw. Sebab Dia telah menebus kita, tubuh dan jiwa, bukan dengan emas atau perak, melainkan dengan darah-Nya yang tak ternilai harganya, sehingga kita bukan lagi hamba dosa, dan telah melepaskan kita dari segala kuasa iblis, dan dengan demikian menjadikan kita milik-Nya (a).

. _Pert. Apa arti perkataan ini: yang dikandung dari Roh Kudus, lahir dari anak dara Maria?_
+
Jaw. Bahwa Anak Allah yang kekal itu, yang tetap (a) tinggal Allah sejati dan kekal (b), telah mengenakan tabiat manusia sejati dari daging dan darah anak dara Maria (c) oleh karya Roh Kudus (d), supaya Dia juga menjadi keturunan Daud yang sejati (e), yang dalam segala hal serupa dengan saudara-saudara-Nya (f),terkecuali dalam hal dosa (g).

. _Pert. Apa manfaat yang Saudara peroleh dari kenyataan bahwa Kristus telah dikandung secara suci dan lahir?_
+
Jaw. Dia adalah Pengantara kita (a), dan karena ketidakbersalahan dan kesucian-Nya yang sempurna maka di hadapan Allah Dia menutupi dosaku yang telah kusandang sejak saat aku dikandung dan dilahirkan.

. _Pert. Apa arti kata menderita menurut Saudara?_
+
Jaw. Artinya, Dia telah menanggung murka Allah atas dosa seluruh umat manusia pada tubuh dan jiwa-Nya (a), selama Dia hidup di dunia ini tetapi terutama pada akhir hidup-Nya. Maksudnya, supaya dengan penderitaan-Nya, sebagai kurban perdamaian satu-satunya (b), Dia melepaskan tubuh dan jiwa kita dari hukuman yang kekal (c), dan memperoleh bagi kita anugerah Allah, kebenaran, dan hidup yang kekal (d).

. _Pert. Mengapa Dia menderita di bawah hakim Pontius Pilatus?_
+
Jaw. Supaya Dia, walaupun tidak bersalah, dihukum di hadapan pengadilan dunia (a), dan dengan demikian meluputkan kita dari hukuman Allah yang keras, yang hendak dilaksanakan atas kita (b).

. _Pert. Apakah kematian-Nya mempunyai arti lebih besar karena terjadi pada kayu salib dibandingkan dengan mati secara lain?_
+
Jaw. Lebih besar artinya, sebab dengan demikian aku mempunyai kepastian, bahwa Dia telah menanggung kutuk yang ada atas diriku (a), mengingat bahwa kematian pada kayu salib itu terkutuk di hadapan Allah (b).

. _Pert. Mengapa Kristus harus merendahkan diri sampai mati?_
+
Jaw. Sebab, menurut keadilan dan kebenaran Allah (a), hutang dosa-dosa kita tidak dapat dilunasi dengan cara lain kecuali dengan kematian Anak Allah (b).

. _Pert. Mengapa Dia dikuburkan?_
+
Jaw. Supaya dengan demikian ditegaskan bahwa Dia telah benar-benar mati (a).

. _Pert. Jika Kristus telah mati untuk kita, mengapa kita juga harus mati?_
+
Jaw. Kematian kita bukanlah pelunasan utang dosa-dosa kita (a), melainkan kematian bagi dosa, dan pintu masuk ke dalam hidup yang kekal (b).

. _Pert. Manfaat apa lagi yang kita peroleh dari pengorbanan dan kematian Kristus pada salib?_
+
Jaw. Oleh kekuatan pengorbanan dan kematian itu, manusia lama kita ikut disalibkan, dimatikan, dan dikuburkan bersama dengan Dia (a), supaya hawa nafsu daging tidak berkuasa lagi dalam diri kita (b), tetapi kita mempersembahkan diri kita menjadi korban syukur bagi-Nya (c).

. _Pert. Mengapa ditambahkan kata-kata turun ke dalam kerajaan maut?_
+
Jaw. Supaya dalam godaan-godaan yang paling sengit sekalipun, aku mendapat keyakinan dan hiburan yang sungguh-sungguh bahwa Tuhanku Yesus Kristus telah melepaskan aku dari ketakutan dan kesakitan neraka (a), oleh ketakutan, nestapa, kegentaran, dan siksa neraka yang tidak terkatakan yang telah diderita-Nya selama masa sengsara-Nya, teristimewa di kayu salib (b).