:page-title     : Method
:page-signed-by : Deo Valiandro. M <valiandrod@gmail.com>
:page-layout    : default
:page-category  : pp
:page-hidden    : true

Method adalah suatu fungsi.

Method melaksanakan suatu tugas tertentu (menurut prinsip SOLID).

Method pada Java memiliki bentuk umum seperti berikut ini:

[source, java]
return-type methodName(parameter-list) {
    //body of method
}

dimana:

. `return-type` adalah jenis nilai yang akan dikembalikan oleh method
tersebut.
. methodName adalah nama method
. parameter-list adalah daftar nilai yang dikirim ke method tersebut.

Contohnya:

sebuah method yang berfungsi untuk menghitung hasil perkalian dua buah bilangan.

[source, java]
public int multipication(int a, int b) {
    return a*b;
}

`int` adalah tipe data yang akan dikembalikan oleh method tersebut, yaitu hasil
perkalian a dengan b. `multipication` adalah nama method tersebut, `int a` dan
`int b` adalah 2 jenis parameter yang diterima oleh method tersebut, parameter
ini akan berguna sebagai nilai yang akan diolah oleh method tersebut.

`public` adalah
link:/2019/05/19/encapsulation.html#access-modifier[access modifier].

Sedangkan untuk memanggil method tersebut, kita dapat memanggil dengan
menggunakan namanya, misalnya kita akan memanggil method yang telah kita buat
diatas:

[source, java]
int hasil = multipication(12, 14);

12 dan 14 disini adalah argumen yang dikirim.

> untuk mengembalikan multiple values, dapat menggunakan return array

Sebuah method juga dapat mengembalikan object. Misalnya:

[source, java]
----
class Demo{
    int a;
    double b;
    int c;

    Demo(int m, double d, int a) {
        a = m;
        b = d;
        c = a;
    }
}

class MethodDemo4{ 
    static Demo get(int x, int y) {
        return new Demo(x * y, (double)x / y, (x + y)); 
    }

    public static void main(String[] args) {
        Demo ans = get(25, 5); 
        System.out.println("Multiplication = " + ans.a); 
        System.out.println("Division = " + ans.b); 
        System.out.println("Addition = " + ans.c); 
    } 
}
----

Sumber: link:{https://www.studytonight.com/java/methods-in-java.php}[https://www.studytonight.com]

> Java menggunakan call-by-value bukan call-by-reference

Note:
1. Tambahkan call-by-value vs call-by-reference
