:page-title     : Array
:page-signed-by : Deo Valiandro. M <valiandrod@gmail.com>
:page-layout    : default
:page-category  : pp
:page-hidden    : true

Array adalah kelompok data dengan tipe yang sama.

Dalam Java, pada saat mendeklarasikan sebuah array panjang array harus
ditentukan, dan tidak dapat diubah setelahnya (nilai fix). Setiap item dalam
sebuah array disebut element, dan setiap element dapat diakses dengan indexnya.
Index array selalu mulai dari 0 sampai n-1, dengan n adalah panjang array.


== Deklarasi

Sebelum digunakan, Array harus dideklarasikan terlebih dahulu dengan
menentukan tipe data dan panjangnya.

Bentuk umum:

[source, java]
tipeData[] namaArray = new tipeData[n];
//atau
tipeData namaArray[] = new tipeData[n];

Contoh:

[source, java]
int[] arr = new int[20];


== Mengisi

Ada beberapa cara untuk menginisialisasi array, diantaranya adalah:

[source, java]
tipeData[] namaArray = { element1, element2, element3, element4 };
//atau
tipeData[] namaArray = new int[4];
namaArray[0] = element1;
namaArray[1] = element2;
namaArray[2] = element3;
namaArray[3] = element4;

Contoh:

[source, java]
int[] arr = { 132, 11, 134, 33};
//atau
int[] arr = new int[4];
arr[0] = 132;
arr[1] = 11;
arr[2] = 134;
arr[3] = 33;


== Mengakses

Untuk mengakses element tertentu pada array cukup dengan menyebutkan nama array
disertai dengan kurung siku dan index element yang ingin diakses.

Bentuk umum:

[source, java]
namaArray[index];

> Indeks array dimulai dari 0

Jadi jika mempunyai data:

[source, java]
int[] arr = { 132, 11, 134, 33};
System.out.println(arr[0]);

akan menampilkan:

[source, bash]
132

dan kemudian diikuti oleh indeks berikutnya.


== Array multi-dimensi

Array multidimensi dapat diilustrasikan sebagai array dalam array. Artinya
setiap element pada array tersebut adalah sebuah array juga (Array dua dimensi).
Hal ini juga berlaku untuk Array NxN dimensi. 

Contoh:

[source, java]
int[][] arr = new int[4][5];

Kemudian untuk mengisinya dengan:

[source, java]
int[][] arr = {
    {1, 1, 1, 1, 1},
    {1, 1, 1, 1, 1},
    {1, 1, 1, 1, 1},
    {1, 1, 1, 1, 1}
};

Untuk mengaksesnya, digunakan cara yang sama dengan array 1-dimensi, misalnya:

[source, java]
System.out.println(arr[0][1]);


== Panjang Array

Untuk menentukan panjang suatu array, digunakan fungsi `.length`.
Contohnya:

[source, java]
int[] arr = { 132, 11, 134, 33};
System.out.println(arr.length);

output:
[source, java]
4

nilainya bukan dihitung dari angka indeks terakhir melainkan jumlah indeknya,
sehingga walaupun indeksnya dimulai dari angka `0` namun panjangnya tetap akan
mengikuti jumlah indeksnya.

Contoh lain:

[source, java]
----
int[][] arr = {
    {1, 1, 1, 1},
    {1, 1, 1, 1, 1},
    {1, 1, 1, 1, 1, 1},
    {1, 1, 1, 1, 1, 1, 1}
};

System.out.println(arr.length);
System.out.println(arr[0].length);
System.out.println(arr[1].length);
----

output:
[source, java]
4
4
5
