:page-title     : Struktur Dasar
:page-signed-by : Deo Valiandro. M <valiandrod@gmail.com>
:page-layout    : default
:page-category  : pp
:page-hidden    : true

Java adalah bahasa pemrograman level tinggi, robust (mempunyai Garbage Collector
dan Exception Handling), object-oriented dan secure/stable tetapi tidak pure
object-oriented language karena masih mendukung primitive data types seperti
int, char, dll. 

Sintaks Java mirip dengan C/C++, tetapi Java tidak mensupport low-level
programming seperti pointer (sebenarnya Java punya pointer. Semua turunan object
adalah pointer. Akan tetapi, anda bisa jadi programmer Java profesional tanpa
perlu tahu fakta inifootnote:[Dari blog https://jekjektuanakal.my.id/post/peta-jalan-pejuang-cpp-2/]).
Kode Java selalu ditulis didalam sebuah class dan objek.


== Struktur program

Struktur dasar sebuah bahasa pemrograman Java adalah sebagai berikut:

[source, java]
public class Main {
    public static void main(String[] args) {
        System.out.println("Hello world!");
    }
}

`class Main` Adalah class utama, nama `Main` harus sesuai dengan nama file.
Aturan penulisannya adalah dengan menggunakan huruf kapital di huruf pertama.
Misalnya: `Main`, `Utama`, dsb-nya.

`public static void main(String args[])` adalah kode utama yang akan dijalankan
ketika kita menjalankan sebuah program Java.


== Aturan Penamaan

Dalam penulisan nama variabel perlu diperhatikan terdapat beberapa aturan khusus
dalam Java yang harus dipatuhi seperti:

1. tidak boleh diawali dengan angka,
2. tidak boleh disertai symbol khusus seperti `@`,`!`,`*`,`#`,
3. tidak boleh menggunakan reserved word sebagai nama variable,
4. boleh diawali dengan underscore atau symbol `$`, dan
5. nama variable tidak boleh mengandung spasi.

Menurut _Convention over configuration Java_, penulisan nama variable 
menggunakan lowerCamel case (misalnya `namaVariabel`), dan penulisan nama class 
menggunakan UpperCamel case (misalnya `Main``).


== Menjalankan program

Java adalah bahasa yang dicompile terlebih dahulu sebelum dirun.

Untuk meng-compile java:

[source, bash]
javac NamaFile.java

dan kemudian akan menghasilkan sebuah file dengan nama `NamaFile.class`.
File inilah yang kemudian dijalankan dengan menggunakan perintah:

[source, bash]
java NamaFile

perhatikan, untuk menjalankan, tidak perlu menggunakan `NamaFile.class`, cukup
dengan menggunakan `NamaFile` saja.

Dengan update dari Java 11, maka sebuah program Java dapat dijalankan tanpa
perlu mengcompilenya terlebih dahulufootnote:[https://openjdk.java.net/jeps/330].

Misalnya:

[source, java]
public class Main {
    public static void main(String[] args) {
        System.out.println("Hello world!");
    }
}

dapat langsung dijalankan dengan:

[source, bash]
java NamaFile.java