:page-title     : Pemrograman Fungsional
:page-signed-by : Deo Valiandro. M <valiandrod@gmail.com>
:page-layout    : default
:page-category  : fp
:page-time      : 2022-02-05T07:12:45
:page-update    : 2022-05-10T13:38:00

> The purpose of software engineering is to control complexity, not to create it.
> -— Dr. Pamela Zave, coauthor of Software Requirements and Design


Functional Programming (FP) merupakan konsep yang baru bagi saya. Ketika
memasuki program studi Ilmu Komputer di Universitas Hasanuddin, saya hanya
dikenalkan dengan pemrograman imperatif dengan Pascal kemudian melompat ke
pengantar pemrograman dengan menggunakan Java.

Ketika dikenalkan dengan paradigma pemrograman, kami langsung dikenalkan dengan
pemrograman berorientasi objek atau PBO/OOP (Eng).

FP kemudian saya dikenal ketika bergabung dengan komunitas di Telegram, yaitu
grup Telegram Haskel. Dari grup inilah kemudian dikenalkan dengan berbagai
konsep fp, namun saya masih kebingungan dengan berbagai jenis konsep fp.

Ketika salah satu anggota grup Haskell mengirim channel youtube
https://www.youtube.com/c/cvladfp, kemudian saya mulai mengenal lebih dalam.

Tulisan ini saya tulis untuk mengawali pelajaran tentang fp.


== Haskell

Contoh fungsi dasar Haskell,

[source, haskell]
----
babyFunction x = x * x
babyFucntion 12
----

[source, bash]
144

Contoh mencari data dalam list,

[source, haskell]
elem' :: (Eq a) => a -> [a] -> Bool  
elem' a [] = False  
elem' a (x:xs)  
    | a == x    = True  
    | otherwise = elem' a xs

is Upper,

[source, haskell]
isUpper :: Char -> Bool
isUpper x = elem x ['A'..'Z']
